/**
 * Aggregates every MMFF94 parameter table into one importable module.
 *
 * Each table is generated by the extraction script
 * (scripts/extract-openbabel-params.py) from OpenBabel's .prm files.
 *
 * The tables are plain TypeScript objects — easy to inspect, easy to debug.
 */

// These will be generated by the extraction script.
// Until the script is run, the imports below will fail to resolve.
// Run: python scripts/extract-openbabel-params.py --input <openbabel/data/MMFF94/> --output src/mmff94/parameters/

// export { ATOM_TYPES } from './atom-types';
// export { BOND_PARAMS } from './bond';
// export { ANGLE_PARAMS } from './angle';
// export { STRETCH_BEND_PARAMS } from './stretch-bend';
// export { TORSION_PARAMS } from './torsion';
// export { VDW_PARAMS } from './van-der-waals';
// export { BCI_PARAMS } from './bci';
// export { OOP_PARAMS } from './out-of-plane';
