/**
 * Aggregates every MMFF94 parameter table into one importable module.
 *
 * Each table is generated by the extraction script
 * (scripts/extract-mmff94-par.py) from OpenBabel's .par files. The
 * class-resolution helpers (parameter-classes.ts) and the empirical
 * rules (empirical.ts) are hand-written and sit beside the tables
 * because they answer the same question: WHICH parameters apply to
 * this bond/angle/torsion.
 *
 * Keys include a leading class column (e.g., "0-1-1", "1-2-2");
 * lookup_param() provides the class-0 fallback, and the class system
 * in parameter-classes.ts selects the class itself.
 */

export { lookup_param } from './lookup.js';
export { ATOM_TYPES } from './atom-types.js';
export { ATOM_TYPE_PROPERTIES, type AtomTypeProperties } from './atom-type-properties.js';
export { BOND_PARAMS } from './bond.js';
export { ANGLE_PARAMS, type AngleParams } from './angle.js';
export { STRETCH_BEND_PARAMS, type StretchBendParams } from './stretch-bend.js';
export { TORSION_PARAMS } from './torsion.js';
export type { TorsionParams } from './torsion.js';
export { VDW_PARAMS } from './van-der-waals.js';
export { BCI_PARAMS, BCI_DEFAULT_PARAMS } from './bci.js';
export { OOP_PARAMS } from './out-of-plane.js';
export { DEFAULT_STRETCH_BEND } from './default-stretch-bend.js';
export {
  make_class_context,
  get_bond_order,
  is_aromatic_bond,
  bond_type_flag,
  angle_class,
  torsion_class,
  strbnd_type,
  bond_parameters,
  angle_parameters,
  lookup_torsion,
  type ClassContext,
} from './parameter-classes.js';
export { ELEMENT_ROW } from './empirical.js';
export { empirical_torsion } from './empirical.js';
