/**
 * Aggregates every MMFF94 parameter table into one importable module.
 *
 * Each table is generated by the extraction script
 * (scripts/extract-mmff94-par.py) from OpenBabel's .par files.
 *
 * Keys include a leading priority column (e.g., "0-1-1", "1-2-2")
 * to handle OpenBabel's multiple-parameter-per-type-convention.
 * Use the lookup_param() helper for correct priority-ordered lookup.
 */

export { lookup_param } from './lookup';
export { ATOM_TYPES } from './atom-types';
export { BOND_PARAMS } from './bond';
export { ANGLE_PARAMS } from './angle';
export { STRETCH_BEND_PARAMS } from './stretch-bend';
export { TORSION_PARAMS } from './torsion';
export { VDW_PARAMS } from './van-der-waals';
export { BCI_PARAMS, BCI_DEFAULT_PARAMS } from './bci';
export { OOP_PARAMS } from './out-of-plane';
