// Auto-generated by scripts/extract-mmff94-par.py
// Priority-ordered parameter lookup helper.
// Do not edit by hand.


/**
 * Look up a parameter entry with priority-ordered fallback.
 *
 * MMFF94 parameter tables store entries keyed as "priority-type1-type2-..."
 * where priority 0 is the default/primary entry and higher numbers are
 * context-specific alternatives. This helper tries entries in priority
 * order (0 first, then 1, 2, ...) and returns the first match.
 *
 * If no match is found, falls back to a wildcard variant where terminal
 * types are replaced with 0.
 */
export function lookup_param<T>(
  table: Record<string, T>,
  types: number[],
  max_priority: number = 5,
): T | undefined {

  // 1. Try exact match with priority 0, then 1, ..., max_priority
  const base_key = types.join('-');
  for (let p = 0; p <= max_priority; p++) {
    const key = `${p}-${base_key}`;
    if (key in table) return table[key];
  }

  // 2. Try with leading type as wildcard (0)
  if (types.length >= 2) {
    const wildcard_lead = [0, ...types.slice(1)].join('-');
    for (let p = 0; p <= max_priority; p++) {
      const key = `${p}-${wildcard_lead}`;
      if (key in table) return table[key];
    }
  }

  // 3. Try with trailing type as wildcard (0)
  if (types.length >= 2) {
    const wildcard_trail = [...types.slice(0, -1), 0].join('-');
    for (let p = 0; p <= max_priority; p++) {
      const key = `${p}-${wildcard_trail}`;
      if (key in table) return table[key];
    }
  }

  // 4. Try with both terminals as wildcard
  if (types.length >= 3) {
    const wildcard_both = [0, ...types.slice(1, -1), 0].join('-');
    for (let p = 0; p <= max_priority; p++) {
      const key = `${p}-${wildcard_both}`;
      if (key in table) return table[key];
    }
  }

  return undefined;
}

/**
 * Like lookup_param, but returns all matching entries (for cases where
 * multiple entries with different priorities are valid, and the caller
 * needs to choose based on context like bond order).
 */
export function lookup_all<T>(
  table: Record<string, T>,
  types: number[],
  max_priority: number = 5,
): T[] {
  const results: T[] = [];
  const base_key = types.join('-');
  for (let p = 0; p <= max_priority; p++) {
    const key = `${p}-${base_key}`;
    if (key in table) results.push(table[key]);
  }
  return results;
}
