// Auto-generated by scripts/extract-mmff94-par.py
// Torsion parameters: up to 3 Fourier terms per entry.
// Do not edit by hand.

export interface TorsionTerm {
  V: number;
  gamma: number;     // phase in degrees
  periodicity: number;
}

export interface TorsionParams {
  terms: TorsionTerm[];
}

export const TORSION_PARAMS: Record<string, TorsionParams> = {
  '0-0-1-1-0': { terms: [
    { V: 0.300, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-1-0': { terms: [
    { V: 0.200, gamma: 0, periodicity: 1 },
    { V: -0.800, gamma: 180, periodicity: 2 },
    { V: 1.500, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-1-1': { terms: [
    { V: 0.103, gamma: 0, periodicity: 1 },
    { V: 0.681, gamma: 180, periodicity: 2 },
    { V: 0.332, gamma: 0, periodicity: 3 }
  ] },
  '5-1-1-1-1': { terms: [
    { V: 0.144, gamma: 0, periodicity: 1 },
    { V: -0.547, gamma: 180, periodicity: 2 },
    { V: 1.126, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-1-2': { terms: [
    { V: -0.295, gamma: 0, periodicity: 1 },
    { V: 0.438, gamma: 180, periodicity: 2 },
    { V: 0.584, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-1-3': { terms: [
    { V: 0.066, gamma: 0, periodicity: 1 },
    { V: -0.156, gamma: 180, periodicity: 2 },
    { V: 0.143, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-1-5': { terms: [
    { V: 0.639, gamma: 0, periodicity: 1 },
    { V: -0.630, gamma: 180, periodicity: 2 },
    { V: 0.264, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-1-6': { terms: [
    { V: -0.688, gamma: 0, periodicity: 1 },
    { V: 1.757, gamma: 180, periodicity: 2 },
    { V: 0.477, gamma: 0, periodicity: 3 }
  ] },
  '5-1-1-1-6': { terms: [
    { V: 0.054, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-1-8': { terms: [
    { V: -1.420, gamma: 0, periodicity: 1 },
    { V: -0.092, gamma: 180, periodicity: 2 },
    { V: 1.101, gamma: 0, periodicity: 3 }
  ] },
  '5-1-1-1-8': { terms: [
    { V: -0.158, gamma: 180, periodicity: 2 },
    { V: 0.323, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-1-11': { terms: [
    { V: 0.593, gamma: 0, periodicity: 1 },
    { V: 0.662, gamma: 180, periodicity: 2 },
    { V: 1.120, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-1-12': { terms: [
    { V: -0.678, gamma: 0, periodicity: 1 },
    { V: 0.417, gamma: 180, periodicity: 2 },
    { V: 0.624, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-1-15': { terms: [
    { V: -0.714, gamma: 0, periodicity: 1 },
    { V: 0.698, gamma: 180, periodicity: 2 }
  ] },
  '0-1-1-1-34': { terms: [
    { V: -0.647, gamma: 0, periodicity: 1 },
    { V: 0.550, gamma: 180, periodicity: 2 },
    { V: 0.590, gamma: 0, periodicity: 3 }
  ] },
  '0-2-1-1-5': { terms: [
    { V: 0.321, gamma: 0, periodicity: 1 },
    { V: -0.411, gamma: 180, periodicity: 2 },
    { V: 0.144, gamma: 0, periodicity: 3 }
  ] },
  '0-3-1-1-3': { terms: [
    { V: 0.443, gamma: 0, periodicity: 1 },
    { V: -1.140, gamma: 0, periodicity: 3 }
  ] },
  '0-3-1-1-5': { terms: [
    { V: -0.256, gamma: 0, periodicity: 1 },
    { V: 0.058, gamma: 180, periodicity: 2 }
  ] },
  '0-3-1-1-6': { terms: [
    { V: -0.679, gamma: 0, periodicity: 1 },
    { V: -0.029, gamma: 180, periodicity: 2 }
  ] },
  '0-5-1-1-5': { terms: [
    { V: 0.284, gamma: 0, periodicity: 1 },
    { V: -1.386, gamma: 180, periodicity: 2 },
    { V: 0.314, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-6': { terms: [
    { V: -0.654, gamma: 0, periodicity: 1 },
    { V: 1.072, gamma: 180, periodicity: 2 },
    { V: 0.279, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-8': { terms: [
    { V: -0.744, gamma: 0, periodicity: 1 },
    { V: -1.235, gamma: 180, periodicity: 2 },
    { V: 0.337, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-10': { terms: [
    { V: 0.427, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-11': { terms: [
    { V: 0.516, gamma: 180, periodicity: 2 },
    { V: 0.291, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-12': { terms: [
    { V: 0.678, gamma: 0, periodicity: 1 },
    { V: -0.602, gamma: 180, periodicity: 2 },
    { V: 0.398, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-15': { terms: [
    { V: 1.142, gamma: 0, periodicity: 1 },
    { V: -0.644, gamma: 180, periodicity: 2 },
    { V: 0.367, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-25': { terms: [
    { V: 0.295, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-34': { terms: [
    { V: 0.692, gamma: 0, periodicity: 1 },
    { V: -0.530, gamma: 180, periodicity: 2 },
    { V: 0.278, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-37': { terms: [
    { V: 0.389, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-39': { terms: [
    { V: 0.278, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-41': { terms: [
    { V: -0.141, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-56': { terms: [
    { V: 0.324, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-1-68': { terms: [
    { V: 0.136, gamma: 0, periodicity: 3 }
  ] },
  '0-6-1-1-6': { terms: [
    { V: 0.408, gamma: 0, periodicity: 1 },
    { V: 1.397, gamma: 180, periodicity: 2 },
    { V: 0.961, gamma: 0, periodicity: 3 }
  ] },
  '5-6-1-1-6': { terms: [
    { V: 0.313, gamma: 0, periodicity: 1 },
    { V: -1.035, gamma: 180, periodicity: 2 },
    { V: 1.631, gamma: 0, periodicity: 3 }
  ] },
  '0-8-1-1-8': { terms: [
    { V: 1.055, gamma: 0, periodicity: 1 },
    { V: 0.834, gamma: 180, periodicity: 2 }
  ] },
  '0-11-1-1-11': { terms: [
    { V: -0.387, gamma: 0, periodicity: 1 },
    { V: -0.543, gamma: 180, periodicity: 2 },
    { V: 1.405, gamma: 0, periodicity: 3 }
  ] },
  '0-12-1-1-12': { terms: [
    { V: 0.893, gamma: 0, periodicity: 3 }
  ] },
  '0-15-1-1-15': { terms: [
    { V: -0.177, gamma: 0, periodicity: 1 },
    { V: 0.049, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-2-0': { terms: [] },
  '2-0-1-2-0': { terms: [] },
  '5-0-1-2-0': { terms: [] },
  '0-0-1-2-2': { terms: [
    { V: -0.650, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-2-2': { terms: [
    { V: -0.650, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-2-1': { terms: [
    { V: 0.419, gamma: 0, periodicity: 1 },
    { V: 0.296, gamma: 180, periodicity: 2 },
    { V: 0.282, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-2-2': { terms: [
    { V: -0.494, gamma: 0, periodicity: 1 },
    { V: 0.274, gamma: 180, periodicity: 2 },
    { V: -0.630, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-2-5': { terms: [
    { V: 0.075, gamma: 0, periodicity: 1 },
    { V: 0.358, gamma: 0, periodicity: 3 }
  ] },
  '0-2-1-2-2': { terms: [
    { V: -0.293, gamma: 0, periodicity: 1 },
    { V: 0.115, gamma: 180, periodicity: 2 },
    { V: -0.508, gamma: 0, periodicity: 3 }
  ] },
  '0-2-1-2-5': { terms: [
    { V: 0.301, gamma: 0, periodicity: 1 },
    { V: 0.104, gamma: 180, periodicity: 2 },
    { V: 0.507, gamma: 0, periodicity: 3 }
  ] },
  '0-3-1-2-1': { terms: [
    { V: 0.565, gamma: 0, periodicity: 1 },
    { V: -0.554, gamma: 180, periodicity: 2 },
    { V: 0.234, gamma: 0, periodicity: 3 }
  ] },
  '0-3-1-2-2': { terms: [
    { V: -0.577, gamma: 0, periodicity: 1 },
    { V: -0.482, gamma: 180, periodicity: 2 },
    { V: -0.427, gamma: 0, periodicity: 3 }
  ] },
  '0-3-1-2-5': { terms: [
    { V: 0.082, gamma: 0, periodicity: 1 },
    { V: 0.123, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-2-1': { terms: [
    { V: -0.184, gamma: 180, periodicity: 2 },
    { V: 0.220, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-2-2': { terms: [
    { V: 0.501, gamma: 0, periodicity: 1 },
    { V: -0.410, gamma: 180, periodicity: 2 },
    { V: -0.535, gamma: 0, periodicity: 3 }
  ] },
  '2-5-1-2-2': { terms: [
    { V: 0.055, gamma: 0, periodicity: 3 }
  ] },
  '2-5-1-2-3': { terms: [
    { V: -0.108, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-2-5': { terms: [
    { V: -0.523, gamma: 0, periodicity: 1 },
    { V: -0.228, gamma: 180, periodicity: 2 },
    { V: 0.208, gamma: 0, periodicity: 3 }
  ] },
  '2-5-1-2-37': { terms: [] },
  '0-6-1-2-1': { terms: [
    { V: -0.467, gamma: 0, periodicity: 1 },
    { V: 0.490, gamma: 0, periodicity: 3 }
  ] },
  '0-6-1-2-2': { terms: [
    { V: 0.425, gamma: 0, periodicity: 1 },
    { V: 0.168, gamma: 180, periodicity: 2 },
    { V: -0.875, gamma: 0, periodicity: 3 }
  ] },
  '0-6-1-2-5': { terms: [
    { V: 0.136, gamma: 180, periodicity: 2 },
    { V: 0.396, gamma: 0, periodicity: 3 }
  ] },
  '0-8-1-2-1': { terms: [
    { V: -0.504, gamma: 0, periodicity: 1 },
    { V: 0.371, gamma: 180, periodicity: 2 },
    { V: 0.557, gamma: 0, periodicity: 3 }
  ] },
  '0-8-1-2-2': { terms: [
    { V: 0.541, gamma: 0, periodicity: 1 },
    { V: 0.539, gamma: 180, periodicity: 2 },
    { V: -1.009, gamma: 0, periodicity: 3 }
  ] },
  '0-8-1-2-5': { terms: [
    { V: 0.204, gamma: 180, periodicity: 2 },
    { V: 0.464, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-3-0': { terms: [
    { V: 0.400, gamma: 180, periodicity: 2 },
    { V: 0.300, gamma: 0, periodicity: 3 }
  ] },
  '2-0-1-3-0': { terms: [
    { V: 0.500, gamma: 180, periodicity: 2 },
    { V: 0.350, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-3-0': { terms: [] },
  '0-0-1-3-1': { terms: [
    { V: 0.550, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-3-5': { terms: [
    { V: 0.200, gamma: 180, periodicity: 2 },
    { V: 0.700, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-3-7': { terms: [
    { V: 0.400, gamma: 180, periodicity: 2 },
    { V: 0.400, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-3-1': { terms: [
    { V: 0.103, gamma: 0, periodicity: 1 },
    { V: 0.177, gamma: 180, periodicity: 2 },
    { V: 0.545, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-3-5': { terms: [
    { V: -0.072, gamma: 0, periodicity: 1 },
    { V: 0.316, gamma: 180, periodicity: 2 },
    { V: 0.674, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-3-6': { terms: [
    { V: -0.117, gamma: 0, periodicity: 1 },
    { V: -0.333, gamma: 180, periodicity: 2 },
    { V: 0.202, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-3-7': { terms: [
    { V: 0.825, gamma: 0, periodicity: 1 },
    { V: 0.139, gamma: 180, periodicity: 2 },
    { V: 0.325, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-3-10': { terms: [
    { V: -0.927, gamma: 0, periodicity: 1 },
    { V: 1.112, gamma: 180, periodicity: 2 },
    { V: 1.388, gamma: 0, periodicity: 3 }
  ] },
  '0-2-1-3-5': { terms: [
    { V: 0.663, gamma: 0, periodicity: 1 },
    { V: -0.167, gamma: 180, periodicity: 2 },
    { V: 0.426, gamma: 0, periodicity: 3 }
  ] },
  '0-2-1-3-7': { terms: [
    { V: -0.758, gamma: 0, periodicity: 1 },
    { V: 0.112, gamma: 180, periodicity: 2 },
    { V: 0.563, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-3-1': { terms: [
    { V: -0.073, gamma: 0, periodicity: 1 },
    { V: 0.085, gamma: 180, periodicity: 2 },
    { V: 0.531, gamma: 0, periodicity: 3 }
  ] },
  '2-5-1-3-2': { terms: [
    { V: 0.115, gamma: 0, periodicity: 3 }
  ] },
  '2-5-1-3-3': { terms: [
    { V: 0.446, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-3-5': { terms: [
    { V: -0.822, gamma: 0, periodicity: 1 },
    { V: 0.501, gamma: 180, periodicity: 2 },
    { V: 1.008, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-3-6': { terms: [
    { V: -0.624, gamma: 180, periodicity: 2 },
    { V: 0.330, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-3-7': { terms: [
    { V: 0.659, gamma: 0, periodicity: 1 },
    { V: -1.407, gamma: 180, periodicity: 2 },
    { V: 0.308, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-3-10': { terms: [
    { V: -0.412, gamma: 0, periodicity: 1 },
    { V: 0.693, gamma: 180, periodicity: 2 },
    { V: 0.087, gamma: 0, periodicity: 3 }
  ] },
  '2-5-1-3-37': { terms: [
    { V: 0.056, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-3-43': { terms: [
    { V: 1.027, gamma: 180, periodicity: 2 },
    { V: 0.360, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-3-51': { terms: [
    { V: 1.543, gamma: 180, periodicity: 2 },
    { V: 0.350, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-3-53': { terms: [
    { V: 0.501, gamma: 180, periodicity: 2 }
  ] },
  '0-5-1-3-74': { terms: [
    { V: 0.513, gamma: 180, periodicity: 2 },
    { V: -0.344, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-3-75': { terms: [
    { V: 0.511, gamma: 180, periodicity: 2 },
    { V: -0.186, gamma: 0, periodicity: 3 }
  ] },
  '0-6-1-3-6': { terms: [
    { V: 0.447, gamma: 0, periodicity: 1 },
    { V: 0.652, gamma: 180, periodicity: 2 },
    { V: 0.318, gamma: 0, periodicity: 3 }
  ] },
  '0-6-1-3-7': { terms: [
    { V: -0.395, gamma: 0, periodicity: 1 },
    { V: 0.730, gamma: 180, periodicity: 2 },
    { V: -0.139, gamma: 0, periodicity: 3 }
  ] },
  '0-10-1-3-7': { terms: [
    { V: 0.338, gamma: 0, periodicity: 1 },
    { V: 2.772, gamma: 180, periodicity: 2 },
    { V: 2.145, gamma: 0, periodicity: 3 }
  ] },
  '0-10-1-3-10': { terms: [
    { V: 0.548, gamma: 0, periodicity: 1 },
    { V: 1.795, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-4-0': { terms: [] },
  '0-0-1-6-0': { terms: [
    { V: 0.200, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-6-0': { terms: [
    { V: -0.200, gamma: 180, periodicity: 2 },
    { V: 0.400, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-6-1': { terms: [
    { V: -0.681, gamma: 0, periodicity: 1 },
    { V: 0.755, gamma: 180, periodicity: 2 },
    { V: 0.755, gamma: 0, periodicity: 3 }
  ] },
  '5-1-1-6-1': { terms: [
    { V: 0.243, gamma: 180, periodicity: 2 },
    { V: -0.596, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-6-3': { terms: [
    { V: -0.547, gamma: 0, periodicity: 1 },
    { V: 0.320, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-6-21': { terms: [
    { V: 0.270, gamma: 180, periodicity: 2 },
    { V: 0.237, gamma: 0, periodicity: 3 }
  ] },
  '0-2-1-6-21': { terms: [
    { V: 0.102, gamma: 0, periodicity: 1 },
    { V: 0.460, gamma: 180, periodicity: 2 },
    { V: -0.128, gamma: 0, periodicity: 3 }
  ] },
  '0-3-1-6-21': { terms: [
    { V: -1.652, gamma: 0, periodicity: 1 },
    { V: -1.660, gamma: 180, periodicity: 2 },
    { V: 0.283, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-6-1': { terms: [
    { V: 0.571, gamma: 0, periodicity: 1 },
    { V: 0.319, gamma: 180, periodicity: 2 },
    { V: 0.570, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-6-2': { terms: [
    { V: 0.306, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-6-3': { terms: [
    { V: 0.572, gamma: 0, periodicity: 1 },
    { V: -0.304, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-6-21': { terms: [
    { V: 0.596, gamma: 0, periodicity: 1 },
    { V: -0.276, gamma: 180, periodicity: 2 },
    { V: 0.346, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-6-25': { terms: [
    { V: 0.061, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-6-37': { terms: [
    { V: 0.106, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-6-45': { terms: [
    { V: -0.174, gamma: 0, periodicity: 3 }
  ] },
  '0-6-1-6-1': { terms: [
    { V: 0.229, gamma: 0, periodicity: 1 },
    { V: -0.710, gamma: 180, periodicity: 2 },
    { V: 0.722, gamma: 0, periodicity: 3 }
  ] },
  '5-6-1-6-1': { terms: [
    { V: 0.040, gamma: 0, periodicity: 3 }
  ] },
  '0-6-1-6-21': { terms: [
    { V: 1.488, gamma: 0, periodicity: 1 },
    { V: -3.401, gamma: 180, periodicity: 2 },
    { V: -0.320, gamma: 0, periodicity: 3 }
  ] },
  '0-37-1-6-21': { terms: [
    { V: 0.712, gamma: 0, periodicity: 1 },
    { V: 1.320, gamma: 180, periodicity: 2 },
    { V: -0.507, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-8-0': { terms: [
    { V: -0.300, gamma: 180, periodicity: 2 },
    { V: 0.500, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-8-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-8-1': { terms: [
    { V: -0.439, gamma: 0, periodicity: 1 },
    { V: 0.786, gamma: 180, periodicity: 2 },
    { V: 0.272, gamma: 0, periodicity: 3 }
  ] },
  '5-1-1-8-1': { terms: [
    { V: 0.115, gamma: 0, periodicity: 1 },
    { V: -0.390, gamma: 180, periodicity: 2 },
    { V: 0.658, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-8-6': { terms: [
    { V: -0.608, gamma: 0, periodicity: 1 },
    { V: 0.339, gamma: 180, periodicity: 2 },
    { V: 1.496, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-8-23': { terms: [
    { V: -0.428, gamma: 0, periodicity: 1 },
    { V: 0.323, gamma: 180, periodicity: 2 },
    { V: 0.280, gamma: 0, periodicity: 3 }
  ] },
  '0-2-1-8-23': { terms: [
    { V: 0.594, gamma: 0, periodicity: 1 },
    { V: -0.409, gamma: 180, periodicity: 2 },
    { V: 0.155, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-8-1': { terms: [
    { V: 0.393, gamma: 0, periodicity: 1 },
    { V: -0.385, gamma: 180, periodicity: 2 },
    { V: 0.562, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-8-6': { terms: [
    { V: 0.598, gamma: 0, periodicity: 1 },
    { V: -0.158, gamma: 180, periodicity: 2 },
    { V: 0.399, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-8-23': { terms: [
    { V: -0.152, gamma: 0, periodicity: 1 },
    { V: -0.440, gamma: 180, periodicity: 2 },
    { V: 0.357, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-9-0': { terms: [] },
  '5-0-1-9-0': { terms: [] },
  '0-5-1-9-3': { terms: [
    { V: 0.204, gamma: 0, periodicity: 1 },
    { V: -0.335, gamma: 180, periodicity: 2 },
    { V: -0.352, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-9-53': { terms: [
    { V: 0.097, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-10-0': { terms: [
    { V: 0.300, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-10-0': { terms: [] },
  '0-0-1-10-3': { terms: [
    { V: 1.000, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-10-3': { terms: [
    { V: -1.027, gamma: 0, periodicity: 1 },
    { V: 0.694, gamma: 180, periodicity: 2 },
    { V: 0.948, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-10-6': { terms: [
    { V: 0.159, gamma: 0, periodicity: 1 },
    { V: -0.552, gamma: 180, periodicity: 2 },
    { V: 0.198, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-10-28': { terms: [
    { V: 0.552, gamma: 0, periodicity: 1 },
    { V: -0.380, gamma: 180, periodicity: 2 },
    { V: 0.326, gamma: 0, periodicity: 3 }
  ] },
  '0-3-1-10-3': { terms: [
    { V: 3.100, gamma: 0, periodicity: 1 },
    { V: -2.529, gamma: 180, periodicity: 2 },
    { V: 1.494, gamma: 0, periodicity: 3 }
  ] },
  '0-3-1-10-28': { terms: [
    { V: 0.079, gamma: 0, periodicity: 1 },
    { V: 0.280, gamma: 180, periodicity: 2 },
    { V: 0.402, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-10-1': { terms: [
    { V: 0.779, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-10-3': { terms: [
    { V: -2.099, gamma: 0, periodicity: 1 },
    { V: 1.363, gamma: 180, periodicity: 2 },
    { V: 0.021, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-10-6': { terms: [
    { V: -0.162, gamma: 0, periodicity: 1 },
    { V: 0.832, gamma: 180, periodicity: 2 },
    { V: 0.552, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-10-28': { terms: [
    { V: -0.616, gamma: 0, periodicity: 1 },
    { V: 0.274, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-15-0': { terms: [
    { V: 0.400, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-15-0': { terms: [
    { V: 0.336, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-15-1': { terms: [
    { V: -1.047, gamma: 0, periodicity: 1 },
    { V: 0.170, gamma: 180, periodicity: 2 },
    { V: 0.398, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-15-15': { terms: [
    { V: -1.438, gamma: 0, periodicity: 1 },
    { V: 0.263, gamma: 180, periodicity: 2 },
    { V: 0.501, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-15-71': { terms: [
    { V: -0.376, gamma: 0, periodicity: 1 },
    { V: -0.133, gamma: 180, periodicity: 2 },
    { V: 0.288, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-15-1': { terms: [
    { V: 1.143, gamma: 0, periodicity: 1 },
    { V: -0.231, gamma: 180, periodicity: 2 },
    { V: 0.447, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-15-15': { terms: [
    { V: 1.555, gamma: 0, periodicity: 1 },
    { V: -0.323, gamma: 180, periodicity: 2 },
    { V: 0.456, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-15-37': { terms: [
    { V: 0.459, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-15-71': { terms: [
    { V: 0.229, gamma: 0, periodicity: 1 },
    { V: 0.203, gamma: 180, periodicity: 2 },
    { V: 0.440, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-17-0': { terms: [
    { V: 0.350, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-17-0': { terms: [] },
  '0-5-1-17-1': { terms: [
    { V: 0.536, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-17-7': { terms: [
    { V: 0.212, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-18-0': { terms: [
    { V: 0.100, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-18-0': { terms: [
    { V: 0.112, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-18-1': { terms: [] },
  '0-5-1-18-6': { terms: [
    { V: 0.099, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-18-32': { terms: [
    { V: 0.585, gamma: 180, periodicity: 2 },
    { V: 0.388, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-18-43': { terms: [
    { V: -0.412, gamma: 180, periodicity: 2 },
    { V: 0.121, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-18-48': { terms: [
    { V: 0.195, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-18-62': { terms: [
    { V: -0.088, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-19-0': { terms: [
    { V: 0.150, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-19-0': { terms: [
    { V: 0.179, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-19-5': { terms: [
    { V: 0.196, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-19-6': { terms: [
    { V: 0.176, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-19-12': { terms: [
    { V: 0.152, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-20-0': { terms: [
    { V: 0.350, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-20-0': { terms: [
    { V: 0.350, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-20-5': { terms: [
    { V: 0.344, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-20-20': { terms: [
    { V: 0.361, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-22-0': { terms: [
    { V: 0.236, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-22-0': { terms: [
    { V: 0.236, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-25-0': { terms: [
    { V: 0.300, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-25-0': { terms: [
    { V: 0.251, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-25-1': { terms: [
    { V: -0.207, gamma: 180, periodicity: 2 },
    { V: 0.232, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-25-32': { terms: [
    { V: 0.288, gamma: 180, periodicity: 2 },
    { V: 0.218, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-25-1': { terms: [
    { V: 0.152, gamma: 180, periodicity: 2 },
    { V: 0.235, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-25-6': { terms: [
    { V: 0.495, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-25-32': { terms: [
    { V: -0.130, gamma: 180, periodicity: 2 },
    { V: 0.214, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-25-43': { terms: [
    { V: 0.466, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-25-72': { terms: [
    { V: 0.243, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-26-0': { terms: [
    { V: 0.450, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-26-0': { terms: [
    { V: 0.376, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-26-12': { terms: [
    { V: 0.439, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-26-71': { terms: [
    { V: 0.472, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-34-0': { terms: [
    { V: 0.250, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-34-0': { terms: [
    { V: 0.198, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-34-36': { terms: [
    { V: 0.187, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-34-1': { terms: [
    { V: 0.247, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-34-36': { terms: [
    { V: 0.259, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-37-0': { terms: [
    { V: 0.200, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-37-0': { terms: [] },
  '0-1-1-37-37': { terms: [
    { V: 0.449, gamma: 180, periodicity: 2 }
  ] },
  '0-5-1-37-37': { terms: [
    { V: -0.420, gamma: 180, periodicity: 2 },
    { V: 0.391, gamma: 0, periodicity: 3 }
  ] },
  '0-6-1-37-37': { terms: [
    { V: 0.150, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-39-0': { terms: [] },
  '5-0-1-39-0': { terms: [] },
  '0-1-1-39-63': { terms: [
    { V: -0.080, gamma: 180, periodicity: 2 },
    { V: -0.056, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-39-63': { terms: [
    { V: -0.113, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-40-0': { terms: [
    { V: 0.250, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-40-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-40-28': { terms: [
    { V: -0.097, gamma: 180, periodicity: 2 },
    { V: 0.203, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-40-37': { terms: [
    { V: 0.329, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-41-0': { terms: [
    { V: 0.600, gamma: 180, periodicity: 2 }
  ] },
  '0-1-1-41-32': { terms: [
    { V: 1.263, gamma: 180, periodicity: 2 }
  ] },
  '0-5-1-41-32': { terms: [
    { V: -0.106, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-41-72': { terms: [
    { V: 0.632, gamma: 180, periodicity: 2 }
  ] },
  '0-0-1-43-0': { terms: [
    { V: 0.150, gamma: 0, periodicity: 3 }
  ] },
  '5-0-1-43-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-43-18': { terms: [
    { V: 0.357, gamma: 0, periodicity: 1 },
    { V: -0.918, gamma: 180, periodicity: 2 }
  ] },
  '0-5-1-43-25': { terms: [
    { V: 0.061, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-43-28': { terms: [
    { V: -0.249, gamma: 0, periodicity: 1 },
    { V: 0.382, gamma: 180, periodicity: 2 },
    { V: 0.343, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-45-0': { terms: [
    { V: 0.100, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-45-32': { terms: [
    { V: 0.125, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-46-0': { terms: [
    { V: -0.500, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-46-7': { terms: [
    { V: -0.540, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-54-0': { terms: [] },
  '2-0-1-54-0': { terms: [] },
  '5-0-1-54-0': { terms: [] },
  '0-5-1-54-3': { terms: [
    { V: -0.315, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-54-36': { terms: [
    { V: 0.315, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-55-0': { terms: [] },
  '5-0-1-55-0': { terms: [] },
  '0-5-1-55-36': { terms: [
    { V: -0.058, gamma: 180, periodicity: 2 },
    { V: 0.084, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-55-57': { terms: [
    { V: -0.058, gamma: 180, periodicity: 2 },
    { V: -0.092, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-56-0': { terms: [
    { V: -0.300, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-56-36': { terms: [
    { V: 0.875, gamma: 0, periodicity: 1 },
    { V: 0.668, gamma: 180, periodicity: 2 },
    { V: -0.015, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-56-57': { terms: [
    { V: -0.870, gamma: 0, periodicity: 1 },
    { V: 0.775, gamma: 180, periodicity: 2 },
    { V: -0.406, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-56-36': { terms: [
    { V: -0.958, gamma: 0, periodicity: 1 },
    { V: -0.629, gamma: 180, periodicity: 2 },
    { V: -0.372, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-56-57': { terms: [
    { V: 0.952, gamma: 0, periodicity: 1 },
    { V: -0.715, gamma: 180, periodicity: 2 },
    { V: -0.483, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-57-0': { terms: [] },
  '5-0-1-57-0': { terms: [] },
  '0-0-1-58-0': { terms: [] },
  '0-0-1-62-0': { terms: [
    { V: 0.250, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-62-18': { terms: [
    { V: 0.270, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-63-0': { terms: [] },
  '5-0-1-63-0': { terms: [] },
  '0-0-1-64-0': { terms: [] },
  '5-0-1-64-0': { terms: [] },
  '0-0-1-67-0': { terms: [] },
  '5-0-1-67-0': { terms: [] },
  '0-0-1-68-0': { terms: [
    { V: 0.400, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-68-1': { terms: [
    { V: -0.117, gamma: 0, periodicity: 1 },
    { V: 0.090, gamma: 180, periodicity: 2 },
    { V: 0.751, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-68-23': { terms: [
    { V: 0.373, gamma: 0, periodicity: 1 },
    { V: 0.153, gamma: 180, periodicity: 2 },
    { V: 0.635, gamma: 0, periodicity: 3 }
  ] },
  '0-1-1-68-32': { terms: [
    { V: -0.090, gamma: 0, periodicity: 1 },
    { V: -0.169, gamma: 180, periodicity: 2 },
    { V: 0.075, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-68-1': { terms: [
    { V: 0.134, gamma: 0, periodicity: 1 },
    { V: -0.112, gamma: 180, periodicity: 2 },
    { V: 0.329, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-68-23': { terms: [
    { V: -0.361, gamma: 0, periodicity: 1 },
    { V: -0.202, gamma: 180, periodicity: 2 },
    { V: 0.560, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-68-32': { terms: [
    { V: 0.072, gamma: 0, periodicity: 1 },
    { V: 0.218, gamma: 180, periodicity: 2 },
    { V: 0.093, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-73-0': { terms: [
    { V: 0.500, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-73-32': { terms: [
    { V: 0.509, gamma: 0, periodicity: 3 }
  ] },
  '0-5-1-73-72': { terms: [
    { V: 0.443, gamma: 0, periodicity: 3 }
  ] },
  '0-0-1-75-0': { terms: [] },
  '0-0-1-78-0': { terms: [] },
  '0-0-1-80-0': { terms: [] },
  '0-0-1-81-0': { terms: [] },
  '0-0-2-2-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-2-2-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '5-0-2-2-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-2-2-1': { terms: [
    { V: -0.403, gamma: 0, periodicity: 1 },
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-2-2-2': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '1-1-2-2-2': { terms: [
    { V: -0.418, gamma: 0, periodicity: 1 },
    { V: 2.089, gamma: 180, periodicity: 2 },
    { V: -0.310, gamma: 0, periodicity: 3 }
  ] },
  '0-1-2-2-5': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '1-1-2-2-5': { terms: [
    { V: 0.412, gamma: 0, periodicity: 1 },
    { V: 2.120, gamma: 180, periodicity: 2 },
    { V: 0.269, gamma: 0, periodicity: 3 }
  ] },
  '1-2-2-2-2': { terms: [
    { V: 0.094, gamma: 0, periodicity: 1 },
    { V: 1.621, gamma: 180, periodicity: 2 },
    { V: 0.877, gamma: 0, periodicity: 3 }
  ] },
  '0-2-2-2-5': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '1-2-2-2-5': { terms: [
    { V: 0.317, gamma: 0, periodicity: 1 },
    { V: 1.421, gamma: 180, periodicity: 2 },
    { V: -0.870, gamma: 0, periodicity: 3 }
  ] },
  '0-3-2-2-5': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-2-2-5': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '1-5-2-2-5': { terms: [
    { V: -0.406, gamma: 0, periodicity: 1 },
    { V: 1.767, gamma: 180, periodicity: 2 }
  ] },
  '0-5-2-2-6': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-2-2-37': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-2-2-40': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-2-2-41': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-2-2-45': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-2-2-62': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-2-3-0': { terms: [
    { V: 2.500, gamma: 180, periodicity: 2 }
  ] },
  '1-1-2-3-1': { terms: [
    { V: 0.136, gamma: 0, periodicity: 1 },
    { V: 1.798, gamma: 180, periodicity: 2 },
    { V: 0.630, gamma: 0, periodicity: 3 }
  ] },
  '1-1-2-3-5': { terms: [
    { V: 0.497, gamma: 0, periodicity: 1 },
    { V: 2.405, gamma: 180, periodicity: 2 },
    { V: 0.357, gamma: 0, periodicity: 3 }
  ] },
  '1-1-2-3-6': { terms: [
    { V: -0.211, gamma: 0, periodicity: 1 },
    { V: 1.925, gamma: 180, periodicity: 2 },
    { V: -0.131, gamma: 0, periodicity: 3 }
  ] },
  '1-1-2-3-7': { terms: [
    { V: -0.401, gamma: 0, periodicity: 1 },
    { V: 2.028, gamma: 180, periodicity: 2 },
    { V: -0.318, gamma: 0, periodicity: 3 }
  ] },
  '1-1-2-3-10': { terms: [
    { V: -0.084, gamma: 0, periodicity: 1 },
    { V: 2.214, gamma: 180, periodicity: 2 },
    { V: -0.610, gamma: 0, periodicity: 3 }
  ] },
  '1-2-2-3-1': { terms: [
    { V: -0.325, gamma: 0, periodicity: 1 },
    { V: 1.553, gamma: 180, periodicity: 2 },
    { V: -0.487, gamma: 0, periodicity: 3 }
  ] },
  '1-2-2-3-5': { terms: [
    { V: -0.295, gamma: 0, periodicity: 1 },
    { V: 2.024, gamma: 180, periodicity: 2 },
    { V: -0.590, gamma: 0, periodicity: 3 }
  ] },
  '1-2-2-3-6': { terms: [
    { V: -0.143, gamma: 0, periodicity: 1 },
    { V: 1.466, gamma: 180, periodicity: 2 }
  ] },
  '1-2-2-3-7': { terms: [
    { V: 0.362, gamma: 0, periodicity: 1 },
    { V: 1.978, gamma: 180, periodicity: 2 }
  ] },
  '1-2-2-3-9': { terms: [
    { V: 0.296, gamma: 0, periodicity: 1 },
    { V: 1.514, gamma: 180, periodicity: 2 },
    { V: 0.481, gamma: 0, periodicity: 3 }
  ] },
  '1-2-2-3-10': { terms: [
    { V: 0.095, gamma: 0, periodicity: 1 },
    { V: 1.583, gamma: 180, periodicity: 2 },
    { V: 0.380, gamma: 0, periodicity: 3 }
  ] },
  '1-5-2-3-1': { terms: [
    { V: 0.213, gamma: 0, periodicity: 1 },
    { V: 1.728, gamma: 180, periodicity: 2 },
    { V: -0.042, gamma: 0, periodicity: 3 }
  ] },
  '1-5-2-3-5': { terms: [
    { V: -0.208, gamma: 0, periodicity: 1 },
    { V: 1.622, gamma: 180, periodicity: 2 },
    { V: 0.223, gamma: 0, periodicity: 3 }
  ] },
  '1-5-2-3-6': { terms: [
    { V: 0.359, gamma: 0, periodicity: 1 },
    { V: 1.539, gamma: 180, periodicity: 2 },
    { V: 0.194, gamma: 0, periodicity: 3 }
  ] },
  '1-5-2-3-7': { terms: [
    { V: 2.046, gamma: 180, periodicity: 2 }
  ] },
  '1-5-2-3-9': { terms: [
    { V: -0.290, gamma: 0, periodicity: 1 },
    { V: 1.519, gamma: 180, periodicity: 2 },
    { V: -0.470, gamma: 0, periodicity: 3 }
  ] },
  '1-5-2-3-10': { terms: [
    { V: 1.395, gamma: 180, periodicity: 2 },
    { V: 0.227, gamma: 0, periodicity: 3 }
  ] },
  '1-0-2-4-0': { terms: [] },
  '0-0-2-6-0': { terms: [
    { V: 3.100, gamma: 180, periodicity: 2 }
  ] },
  '2-0-2-6-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '5-0-2-6-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-2-2-6-1': { terms: [
    { V: -1.953, gamma: 0, periodicity: 1 },
    { V: 3.953, gamma: 180, periodicity: 2 },
    { V: -1.055, gamma: 0, periodicity: 3 }
  ] },
  '0-2-2-6-3': { terms: [
    { V: -1.712, gamma: 0, periodicity: 1 },
    { V: 2.596, gamma: 180, periodicity: 2 },
    { V: -0.330, gamma: 0, periodicity: 3 }
  ] },
  '0-2-2-6-29': { terms: [
    { V: -0.215, gamma: 0, periodicity: 1 },
    { V: 2.810, gamma: 180, periodicity: 2 },
    { V: -0.456, gamma: 0, periodicity: 3 }
  ] },
  '0-5-2-6-1': { terms: [
    { V: 1.951, gamma: 0, periodicity: 1 },
    { V: 3.936, gamma: 180, periodicity: 2 },
    { V: 1.130, gamma: 0, periodicity: 3 }
  ] },
  '0-5-2-6-3': { terms: [
    { V: 1.719, gamma: 0, periodicity: 1 },
    { V: 2.628, gamma: 180, periodicity: 2 },
    { V: 0.360, gamma: 0, periodicity: 3 }
  ] },
  '0-5-2-6-29': { terms: [
    { V: 0.216, gamma: 0, periodicity: 1 },
    { V: 2.808, gamma: 180, periodicity: 2 },
    { V: 0.456, gamma: 0, periodicity: 3 }
  ] },
  '1-0-2-9-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-10-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '2-0-2-10-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '5-0-2-10-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-15-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '2-0-2-15-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '5-0-2-15-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-17-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-18-0': { terms: [] },
  '2-0-2-18-0': { terms: [] },
  '5-0-2-18-0': { terms: [] },
  '0-0-2-19-0': { terms: [] },
  '0-0-2-20-0': { terms: [] },
  '2-0-2-20-0': { terms: [] },
  '0-0-2-22-0': { terms: [] },
  '2-0-2-22-0': { terms: [] },
  '5-0-2-22-0': { terms: [] },
  '0-0-2-25-0': { terms: [] },
  '0-0-2-30-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-34-0': { terms: [] },
  '2-0-2-34-0': { terms: [] },
  '1-0-2-37-0': { terms: [
    { V: 2.000, gamma: 180, periodicity: 2 }
  ] },
  '1-1-2-37-37': { terms: [
    { V: 2.952, gamma: 180, periodicity: 2 },
    { V: -0.079, gamma: 0, periodicity: 3 }
  ] },
  '1-2-2-37-37': { terms: [
    { V: 1.542, gamma: 180, periodicity: 2 },
    { V: 0.434, gamma: 0, periodicity: 3 }
  ] },
  '1-5-2-37-37': { terms: [
    { V: 1.308, gamma: 180, periodicity: 2 },
    { V: -0.357, gamma: 0, periodicity: 3 }
  ] },
  '1-0-2-39-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-40-0': { terms: [
    { V: 3.700, gamma: 180, periodicity: 2 }
  ] },
  '2-0-2-40-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '5-0-2-40-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-2-2-40-28': { terms: [
    { V: 3.756, gamma: 180, periodicity: 2 },
    { V: -0.530, gamma: 0, periodicity: 3 }
  ] },
  '0-5-2-40-28': { terms: [
    { V: 0.073, gamma: 0, periodicity: 1 },
    { V: 3.698, gamma: 180, periodicity: 2 },
    { V: 0.291, gamma: 0, periodicity: 3 }
  ] },
  '0-0-2-41-0': { terms: [
    { V: 1.200, gamma: 180, periodicity: 2 }
  ] },
  '2-0-2-41-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-2-2-41-32': { terms: [
    { V: 1.235, gamma: 180, periodicity: 2 }
  ] },
  '0-5-2-41-32': { terms: [
    { V: 1.231, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-43-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '2-0-2-43-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-45-0': { terms: [
    { V: 2.200, gamma: 180, periodicity: 2 }
  ] },
  '2-0-2-45-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-2-2-45-32': { terms: [
    { V: 2.212, gamma: 180, periodicity: 2 }
  ] },
  '0-5-2-45-32': { terms: [
    { V: 2.225, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-46-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '2-0-2-46-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-55-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-56-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-2-62-0': { terms: [
    { V: 8.000, gamma: 180, periodicity: 2 }
  ] },
  '0-2-2-62-23': { terms: [
    { V: 1.693, gamma: 0, periodicity: 1 },
    { V: 7.903, gamma: 180, periodicity: 2 },
    { V: 0.532, gamma: 0, periodicity: 3 }
  ] },
  '0-5-2-62-23': { terms: [
    { V: -1.696, gamma: 0, periodicity: 1 },
    { V: 7.897, gamma: 180, periodicity: 2 },
    { V: -0.482, gamma: 0, periodicity: 3 }
  ] },
  '1-0-2-63-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-2-64-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-2-67-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-2-81-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-3-3-0': { terms: [
    { V: 0.600, gamma: 180, periodicity: 2 }
  ] },
  '4-0-3-3-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-1-3-3-1': { terms: [
    { V: -0.486, gamma: 0, periodicity: 1 },
    { V: 0.714, gamma: 180, periodicity: 2 }
  ] },
  '1-1-3-3-6': { terms: [
    { V: -0.081, gamma: 0, periodicity: 1 },
    { V: -0.125, gamma: 180, periodicity: 2 },
    { V: 0.132, gamma: 0, periodicity: 3 }
  ] },
  '1-1-3-3-7': { terms: [
    { V: 1.053, gamma: 0, periodicity: 1 },
    { V: 1.327, gamma: 180, periodicity: 2 }
  ] },
  '1-5-3-3-6': { terms: [
    { V: 0.188, gamma: 180, periodicity: 2 },
    { V: 0.436, gamma: 0, periodicity: 3 }
  ] },
  '1-5-3-3-7': { terms: [
    { V: 0.177, gamma: 180, periodicity: 2 },
    { V: -0.412, gamma: 0, periodicity: 3 }
  ] },
  '1-6-3-3-6': { terms: [
    { V: 0.269, gamma: 0, periodicity: 1 },
    { V: 0.437, gamma: 180, periodicity: 2 }
  ] },
  '1-6-3-3-7': { terms: [
    { V: -0.495, gamma: 0, periodicity: 1 },
    { V: 0.793, gamma: 180, periodicity: 2 },
    { V: -0.318, gamma: 0, periodicity: 3 }
  ] },
  '1-7-3-3-7': { terms: [
    { V: -0.260, gamma: 0, periodicity: 1 },
    { V: 1.084, gamma: 180, periodicity: 2 },
    { V: 0.193, gamma: 0, periodicity: 3 }
  ] },
  '0-0-3-6-0': { terms: [
    { V: 5.500, gamma: 180, periodicity: 2 }
  ] },
  '2-0-3-6-0': { terms: [
    { V: 5.500, gamma: 180, periodicity: 2 }
  ] },
  '4-0-3-6-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '5-0-3-6-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-1-3-6-1': { terms: [
    { V: -1.244, gamma: 0, periodicity: 1 },
    { V: 5.482, gamma: 180, periodicity: 2 },
    { V: 0.365, gamma: 0, periodicity: 3 }
  ] },
  '0-1-3-6-24': { terms: [
    { V: -1.166, gamma: 0, periodicity: 1 },
    { V: 5.078, gamma: 180, periodicity: 2 },
    { V: -0.545, gamma: 0, periodicity: 3 }
  ] },
  '0-1-3-6-37': { terms: [
    { V: -0.677, gamma: 0, periodicity: 1 },
    { V: 5.854, gamma: 180, periodicity: 2 },
    { V: 0.521, gamma: 0, periodicity: 3 }
  ] },
  '2-2-3-6-24': { terms: [
    { V: 0.256, gamma: 0, periodicity: 1 },
    { V: 4.519, gamma: 180, periodicity: 2 },
    { V: 0.258, gamma: 0, periodicity: 3 }
  ] },
  '2-3-3-6-24': { terms: [
    { V: 1.663, gamma: 0, periodicity: 1 },
    { V: 4.073, gamma: 180, periodicity: 2 },
    { V: 0.094, gamma: 0, periodicity: 3 }
  ] },
  '0-5-3-6-1': { terms: [
    { V: 0.526, gamma: 0, periodicity: 1 },
    { V: 5.631, gamma: 180, periodicity: 2 },
    { V: 0.691, gamma: 0, periodicity: 3 }
  ] },
  '0-5-3-6-2': { terms: [
    { V: 0.159, gamma: 0, periodicity: 1 },
    { V: 6.586, gamma: 180, periodicity: 2 },
    { V: 0.216, gamma: 0, periodicity: 3 }
  ] },
  '0-5-3-6-24': { terms: [
    { V: -2.285, gamma: 0, periodicity: 1 },
    { V: 4.737, gamma: 180, periodicity: 2 },
    { V: 0.468, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-6-0': { terms: [
    { V: 0.700, gamma: 0, periodicity: 1 },
    { V: 6.500, gamma: 180, periodicity: 2 },
    { V: -0.400, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-6-1': { terms: [
    { V: 0.682, gamma: 0, periodicity: 1 },
    { V: 7.184, gamma: 180, periodicity: 2 },
    { V: -0.935, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-6-2': { terms: [
    { V: -0.168, gamma: 0, periodicity: 1 },
    { V: 6.572, gamma: 180, periodicity: 2 },
    { V: -0.151, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-6-24': { terms: [
    { V: 1.662, gamma: 0, periodicity: 1 },
    { V: 6.152, gamma: 180, periodicity: 2 },
    { V: -0.058, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-6-37': { terms: [
    { V: 0.635, gamma: 0, periodicity: 1 },
    { V: 5.890, gamma: 180, periodicity: 2 },
    { V: -0.446, gamma: 0, periodicity: 3 }
  ] },
  '2-37-3-6-24': { terms: [
    { V: 3.892, gamma: 180, periodicity: 2 },
    { V: -0.094, gamma: 0, periodicity: 3 }
  ] },
  '0-0-3-9-0': { terms: [
    { V: 16.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-3-9-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '5-0-3-9-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-2-3-9-27': { terms: [
    { V: 16.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-3-9-1': { terms: [
    { V: 0.687, gamma: 0, periodicity: 1 },
    { V: 16.152, gamma: 180, periodicity: 2 },
    { V: 0.894, gamma: 0, periodicity: 3 }
  ] },
  '0-5-3-9-27': { terms: [
    { V: 16.000, gamma: 180, periodicity: 2 }
  ] },
  '0-40-3-9-1': { terms: [
    { V: -0.758, gamma: 0, periodicity: 1 },
    { V: 18.216, gamma: 180, periodicity: 2 },
    { V: -0.188, gamma: 0, periodicity: 3 }
  ] },
  '0-40-3-9-27': { terms: [
    { V: 16.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-10-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '2-0-3-10-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '4-0-3-10-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '5-0-3-10-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-3-10-1': { terms: [
    { V: 0.647, gamma: 0, periodicity: 1 },
    { V: 6.159, gamma: 180, periodicity: 2 },
    { V: 0.507, gamma: 0, periodicity: 3 }
  ] },
  '0-1-3-10-6': { terms: [
    { V: -1.035, gamma: 0, periodicity: 1 },
    { V: 8.791, gamma: 180, periodicity: 2 },
    { V: 1.464, gamma: 0, periodicity: 3 }
  ] },
  '0-1-3-10-28': { terms: [
    { V: -0.294, gamma: 0, periodicity: 1 },
    { V: 5.805, gamma: 180, periodicity: 2 },
    { V: 1.342, gamma: 0, periodicity: 3 }
  ] },
  '2-2-3-10-28': { terms: [
    { V: -0.287, gamma: 0, periodicity: 1 },
    { V: 7.142, gamma: 180, periodicity: 2 },
    { V: 0.120, gamma: 0, periodicity: 3 }
  ] },
  '0-5-3-10-1': { terms: [
    { V: -0.183, gamma: 0, periodicity: 1 },
    { V: 6.314, gamma: 180, periodicity: 2 },
    { V: 1.753, gamma: 0, periodicity: 3 }
  ] },
  '0-5-3-10-3': { terms: [
    { V: -0.751, gamma: 0, periodicity: 1 },
    { V: 5.348, gamma: 180, periodicity: 2 },
    { V: 0.209, gamma: 0, periodicity: 3 }
  ] },
  '0-5-3-10-28': { terms: [
    { V: -0.388, gamma: 0, periodicity: 1 },
    { V: 5.972, gamma: 180, periodicity: 2 },
    { V: 0.459, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-10-1': { terms: [
    { V: -0.319, gamma: 0, periodicity: 1 },
    { V: 6.294, gamma: 180, periodicity: 2 },
    { V: -0.147, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-10-3': { terms: [
    { V: 0.776, gamma: 0, periodicity: 1 },
    { V: -0.585, gamma: 180, periodicity: 2 },
    { V: -0.145, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-10-6': { terms: [
    { V: 1.107, gamma: 0, periodicity: 1 },
    { V: 8.631, gamma: 180, periodicity: 2 },
    { V: -0.452, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-10-28': { terms: [
    { V: 1.435, gamma: 0, periodicity: 1 },
    { V: 4.975, gamma: 180, periodicity: 2 },
    { V: -0.454, gamma: 0, periodicity: 3 }
  ] },
  '0-10-3-10-28': { terms: [
    { V: 3.495, gamma: 180, periodicity: 2 },
    { V: 1.291, gamma: 0, periodicity: 3 }
  ] },
  '0-0-3-15-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '2-0-3-15-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '4-0-3-15-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '5-0-3-15-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-17-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '5-0-3-17-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-18-0': { terms: [] },
  '2-0-3-18-0': { terms: [] },
  '0-0-3-20-0': { terms: [
    { V: -0.300, gamma: 0, periodicity: 3 }
  ] },
  '2-0-3-20-0': { terms: [] },
  '4-0-3-20-0': { terms: [
    { V: -0.300, gamma: 0, periodicity: 3 }
  ] },
  '5-0-3-20-0': { terms: [] },
  '0-7-3-20-0': { terms: [
    { V: 0.400, gamma: 180, periodicity: 2 },
    { V: 0.400, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-20-5': { terms: [
    { V: -0.131, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-20-20': { terms: [] },
  '0-20-3-20-5': { terms: [
    { V: 0.085, gamma: 0, periodicity: 3 }
  ] },
  '0-20-3-20-20': { terms: [] },
  '0-0-3-22-0': { terms: [] },
  '2-0-3-22-0': { terms: [] },
  '4-0-3-22-0': { terms: [] },
  '5-0-3-22-0': { terms: [] },
  '0-7-3-22-0': { terms: [
    { V: 0.400, gamma: 180, periodicity: 2 },
    { V: 0.400, gamma: 0, periodicity: 3 }
  ] },
  '0-0-3-25-0': { terms: [] },
  '2-0-3-25-0': { terms: [] },
  '1-0-3-30-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '4-0-3-30-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-3-37-0': { terms: [
    { V: 2.500, gamma: 180, periodicity: 2 }
  ] },
  '4-0-3-37-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-1-3-37-37': { terms: [
    { V: 2.428, gamma: 180, periodicity: 2 }
  ] },
  '1-6-3-37-37': { terms: [
    { V: 1.743, gamma: 180, periodicity: 2 }
  ] },
  '1-7-3-37-37': { terms: [
    { V: 2.256, gamma: 180, periodicity: 2 }
  ] },
  '1-43-3-37-37': { terms: [
    { V: -0.241, gamma: 0, periodicity: 1 },
    { V: 3.385, gamma: 180, periodicity: 2 },
    { V: -0.838, gamma: 0, periodicity: 3 }
  ] },
  '1-0-3-39-0': { terms: [
    { V: 5.500, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-40-0': { terms: [
    { V: 3.900, gamma: 180, periodicity: 2 }
  ] },
  '2-0-3-40-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '5-0-3-40-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-5-3-40-28': { terms: [
    { V: -1.477, gamma: 0, periodicity: 1 },
    { V: 4.362, gamma: 180, periodicity: 2 },
    { V: 0.902, gamma: 0, periodicity: 3 }
  ] },
  '0-9-3-40-28': { terms: [
    { V: 1.496, gamma: 0, periodicity: 1 },
    { V: 4.369, gamma: 180, periodicity: 2 },
    { V: -0.417, gamma: 0, periodicity: 3 }
  ] },
  '0-40-3-40-28': { terms: [
    { V: 0.178, gamma: 0, periodicity: 1 },
    { V: 3.149, gamma: 180, periodicity: 2 },
    { V: 0.778, gamma: 0, periodicity: 3 }
  ] },
  '0-0-3-41-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '2-0-3-41-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-43-0': { terms: [
    { V: 4.500, gamma: 180, periodicity: 2 }
  ] },
  '2-0-3-43-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '4-0-3-43-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '5-0-3-43-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-1-3-43-18': { terms: [
    { V: 1.712, gamma: 0, periodicity: 1 },
    { V: 3.309, gamma: 180, periodicity: 2 },
    { V: 0.233, gamma: 0, periodicity: 3 }
  ] },
  '0-1-3-43-28': { terms: [
    { V: -0.414, gamma: 0, periodicity: 1 },
    { V: 4.168, gamma: 180, periodicity: 2 },
    { V: -0.875, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-43-18': { terms: [
    { V: -0.880, gamma: 0, periodicity: 1 },
    { V: 5.091, gamma: 180, periodicity: 2 },
    { V: -0.129, gamma: 0, periodicity: 3 }
  ] },
  '0-7-3-43-28': { terms: [
    { V: 0.536, gamma: 0, periodicity: 1 },
    { V: 5.276, gamma: 180, periodicity: 2 },
    { V: -0.556, gamma: 0, periodicity: 3 }
  ] },
  '2-37-3-43-18': { terms: [
    { V: -0.701, gamma: 0, periodicity: 1 },
    { V: 4.871, gamma: 180, periodicity: 2 },
    { V: 1.225, gamma: 0, periodicity: 3 }
  ] },
  '2-37-3-43-28': { terms: [
    { V: -0.086, gamma: 0, periodicity: 1 },
    { V: 5.073, gamma: 180, periodicity: 2 },
    { V: 0.878, gamma: 0, periodicity: 3 }
  ] },
  '0-0-3-45-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '2-0-3-45-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-48-0': { terms: [
    { V: 0.892, gamma: 0, periodicity: 3 }
  ] },
  '0-0-3-51-0': { terms: [
    { V: 13.500, gamma: 180, periodicity: 2 }
  ] },
  '0-1-3-51-52': { terms: [
    { V: 13.549, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-54-0': { terms: [
    { V: 8.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-3-54-0': { terms: [
    { V: 2.500, gamma: 180, periodicity: 2 }
  ] },
  '5-0-3-54-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-3-54-1': { terms: [
    { V: 8.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-3-54-36': { terms: [
    { V: 8.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-55-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '2-0-3-55-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-56-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '2-0-3-56-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-3-57-0': { terms: [
    { V: 2.500, gamma: 180, periodicity: 2 }
  ] },
  '1-0-3-58-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-62-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '2-0-3-62-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '5-0-3-62-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '1-0-3-63-0': { terms: [
    { V: 2.500, gamma: 180, periodicity: 2 }
  ] },
  '1-0-3-64-0': { terms: [
    { V: 2.500, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-67-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-74-0': { terms: [
    { V: 19.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-3-74-7': { terms: [
    { V: 19.349, gamma: 180, periodicity: 2 }
  ] },
  '0-0-3-75-0': { terms: [
    { V: 19.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-3-75-71': { terms: [
    { V: 18.751, gamma: 180, periodicity: 2 }
  ] },
  '1-0-3-78-0': { terms: [
    { V: 2.500, gamma: 180, periodicity: 2 }
  ] },
  '1-0-3-80-0': { terms: [
    { V: 2.500, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-6-0': { terms: [
    { V: -2.000, gamma: 180, periodicity: 2 }
  ] },
  '5-0-6-6-0': { terms: [
    { V: -2.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-8-0': { terms: [
    { V: 0.900, gamma: 0, periodicity: 1 },
    { V: -1.100, gamma: 180, periodicity: 2 },
    { V: -0.500, gamma: 0, periodicity: 3 }
  ] },
  '5-0-6-8-0': { terms: [
    { V: 0.274, gamma: 0, periodicity: 3 }
  ] },
  '0-21-6-8-1': { terms: [
    { V: 0.261, gamma: 0, periodicity: 1 },
    { V: -0.330, gamma: 180, periodicity: 2 },
    { V: -0.542, gamma: 0, periodicity: 3 }
  ] },
  '0-21-6-8-23': { terms: [
    { V: 1.503, gamma: 0, periodicity: 1 },
    { V: -1.853, gamma: 180, periodicity: 2 },
    { V: -0.476, gamma: 0, periodicity: 3 }
  ] },
  '0-0-6-9-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '5-0-6-9-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-10-0': { terms: [
    { V: 1.200, gamma: 0, periodicity: 1 },
    { V: 0.500, gamma: 180, periodicity: 2 },
    { V: -1.000, gamma: 0, periodicity: 3 }
  ] },
  '0-21-6-10-1': { terms: [
    { V: 0.875, gamma: 0, periodicity: 1 },
    { V: 0.180, gamma: 180, periodicity: 2 },
    { V: -0.733, gamma: 0, periodicity: 3 }
  ] },
  '0-21-6-10-3': { terms: [
    { V: 0.529, gamma: 0, periodicity: 1 },
    { V: -1.163, gamma: 0, periodicity: 3 }
  ] },
  '0-0-6-15-0': { terms: [
    { V: -4.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-17-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '5-0-6-17-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-18-0': { terms: [
    { V: 0.100, gamma: 0, periodicity: 3 }
  ] },
  '5-0-6-18-0': { terms: [
    { V: 0.103, gamma: 0, periodicity: 3 }
  ] },
  '0-33-6-18-1': { terms: [
    { V: -0.520, gamma: 0, periodicity: 1 },
    { V: -0.471, gamma: 180, periodicity: 2 },
    { V: -0.267, gamma: 0, periodicity: 3 }
  ] },
  '0-33-6-18-6': { terms: [
    { V: -1.623, gamma: 0, periodicity: 1 },
    { V: 0.204, gamma: 180, periodicity: 2 },
    { V: 0.438, gamma: 0, periodicity: 3 }
  ] },
  '0-33-6-18-32': { terms: [
    { V: 1.616, gamma: 0, periodicity: 1 },
    { V: 0.425, gamma: 180, periodicity: 2 },
    { V: 0.191, gamma: 0, periodicity: 3 }
  ] },
  '0-0-6-19-0': { terms: [
    { V: 0.150, gamma: 0, periodicity: 3 }
  ] },
  '5-0-6-19-0': { terms: [
    { V: 0.165, gamma: 0, periodicity: 3 }
  ] },
  '0-21-6-19-1': { terms: [
    { V: -0.620, gamma: 0, periodicity: 1 },
    { V: -0.329, gamma: 180, periodicity: 2 },
    { V: 0.303, gamma: 0, periodicity: 3 }
  ] },
  '0-21-6-19-5': { terms: [
    { V: 0.683, gamma: 0, periodicity: 1 },
    { V: 0.220, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-20-0': { terms: [
    { V: 0.400, gamma: 0, periodicity: 3 }
  ] },
  '4-0-6-20-0': { terms: [
    { V: 0.217, gamma: 0, periodicity: 3 }
  ] },
  '5-0-6-20-0': { terms: [
    { V: 0.217, gamma: 0, periodicity: 3 }
  ] },
  '0-20-6-20-5': { terms: [
    { V: -0.079, gamma: 0, periodicity: 3 }
  ] },
  '4-20-6-20-20': { terms: [] },
  '0-0-6-22-0': { terms: [
    { V: 0.217, gamma: 0, periodicity: 3 }
  ] },
  '0-0-6-25-0': { terms: [
    { V: 0.650, gamma: 0, periodicity: 3 }
  ] },
  '5-0-6-25-0': { terms: [
    { V: 0.231, gamma: 0, periodicity: 3 }
  ] },
  '0-1-6-25-1': { terms: [
    { V: -1.704, gamma: 0, periodicity: 1 },
    { V: -0.452, gamma: 180, periodicity: 2 },
    { V: 0.556, gamma: 0, periodicity: 3 }
  ] },
  '0-1-6-25-6': { terms: [
    { V: 0.777, gamma: 0, periodicity: 3 }
  ] },
  '0-1-6-25-32': { terms: [
    { V: 1.205, gamma: 0, periodicity: 1 },
    { V: 0.914, gamma: 180, periodicity: 2 },
    { V: 0.612, gamma: 0, periodicity: 3 }
  ] },
  '0-24-6-25-6': { terms: [
    { V: -3.209, gamma: 0, periodicity: 1 },
    { V: -7.622, gamma: 180, periodicity: 2 },
    { V: 1.065, gamma: 0, periodicity: 3 }
  ] },
  '0-24-6-25-32': { terms: [
    { V: -5.891, gamma: 0, periodicity: 1 },
    { V: -3.332, gamma: 180, periodicity: 2 },
    { V: 0.290, gamma: 0, periodicity: 3 }
  ] },
  '0-0-6-26-0': { terms: [
    { V: 0.346, gamma: 0, periodicity: 3 }
  ] },
  '0-0-6-30-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '2-0-6-30-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-37-0': { terms: [
    { V: 3.200, gamma: 180, periodicity: 2 }
  ] },
  '5-0-6-37-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-1-6-37-37': { terms: [
    { V: 4.382, gamma: 180, periodicity: 2 }
  ] },
  '0-3-6-37-37': { terms: [
    { V: 2.576, gamma: 180, periodicity: 2 }
  ] },
  '0-29-6-37-37': { terms: [
    { V: 2.801, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-39-0': { terms: [] },
  '0-0-6-40-0': { terms: [
    { V: 0.274, gamma: 0, periodicity: 3 }
  ] },
  '0-0-6-41-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-43-0': { terms: [
    { V: 0.274, gamma: 0, periodicity: 3 }
  ] },
  '0-0-6-45-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-6-45-32': { terms: [
    { V: 6.208, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-54-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-55-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-57-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-58-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-63-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-6-64-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-8-8-0': { terms: [
    { V: 0.375, gamma: 0, periodicity: 3 }
  ] },
  '5-0-8-8-0': { terms: [
    { V: 0.375, gamma: 0, periodicity: 3 }
  ] },
  '0-0-8-9-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '5-0-8-9-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-8-10-0': { terms: [] },
  '4-0-8-10-0': { terms: [] },
  '0-0-8-15-0': { terms: [
    { V: 0.424, gamma: 0, periodicity: 3 }
  ] },
  '0-0-8-17-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '4-0-8-17-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '5-0-8-17-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-8-19-0': { terms: [
    { V: 0.225, gamma: 0, periodicity: 3 }
  ] },
  '0-0-8-20-0': { terms: [
    { V: 0.350, gamma: 0, periodicity: 3 }
  ] },
  '4-0-8-20-0': { terms: [
    { V: 0.300, gamma: 0, periodicity: 3 }
  ] },
  '5-0-8-20-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '0-20-8-20-5': { terms: [
    { V: 0.120, gamma: 180, periodicity: 2 },
    { V: 0.472, gamma: 0, periodicity: 3 }
  ] },
  '4-20-8-20-20': { terms: [
    { V: -0.097, gamma: 180, periodicity: 2 },
    { V: 0.200, gamma: 0, periodicity: 3 }
  ] },
  '0-23-8-20-5': { terms: [
    { V: -0.101, gamma: 0, periodicity: 1 },
    { V: -0.324, gamma: 180, periodicity: 2 },
    { V: 0.371, gamma: 0, periodicity: 3 }
  ] },
  '0-23-8-20-20': { terms: [
    { V: 0.107, gamma: 0, periodicity: 1 },
    { V: 0.253, gamma: 180, periodicity: 2 },
    { V: 0.151, gamma: 0, periodicity: 3 }
  ] },
  '0-0-8-22-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '0-0-8-25-0': { terms: [
    { V: 0.316, gamma: 0, periodicity: 3 }
  ] },
  '5-0-8-25-0': { terms: [
    { V: 0.316, gamma: 0, periodicity: 3 }
  ] },
  '0-0-8-26-0': { terms: [
    { V: 0.474, gamma: 0, periodicity: 3 }
  ] },
  '5-0-8-26-0': { terms: [
    { V: 0.474, gamma: 0, periodicity: 3 }
  ] },
  '0-0-8-34-0': { terms: [
    { V: 0.250, gamma: 0, periodicity: 3 }
  ] },
  '0-0-8-39-0': { terms: [] },
  '0-0-8-40-0': { terms: [
    { V: 0.375, gamma: 0, periodicity: 3 }
  ] },
  '0-0-8-43-0': { terms: [
    { V: 0.375, gamma: 0, periodicity: 3 }
  ] },
  '0-0-8-45-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-8-46-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-8-55-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-8-56-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-9-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-9-9-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '5-0-9-9-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-10-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '5-0-9-10-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-15-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-18-0': { terms: [] },
  '0-0-9-19-0': { terms: [] },
  '0-0-9-20-0': { terms: [] },
  '0-0-9-25-0': { terms: [] },
  '0-0-9-34-0': { terms: [] },
  '5-0-9-34-0': { terms: [] },
  '1-0-9-37-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-9-39-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-40-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-41-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-45-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-54-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-55-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-56-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-9-57-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-62-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '1-0-9-63-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-9-64-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-9-67-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-9-78-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-9-81-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-10-10-0': { terms: [] },
  '5-0-10-10-0': { terms: [] },
  '0-0-10-15-0': { terms: [] },
  '0-0-10-17-0': { terms: [
    { V: 4.743, gamma: 180, periodicity: 2 }
  ] },
  '0-0-10-20-0': { terms: [] },
  '4-0-10-20-0': { terms: [] },
  '5-0-10-20-0': { terms: [] },
  '0-0-10-22-0': { terms: [] },
  '0-0-10-25-0': { terms: [] },
  '0-0-10-26-0': { terms: [] },
  '5-0-10-26-0': { terms: [] },
  '0-0-10-34-0': { terms: [] },
  '0-0-10-37-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-10-39-0': { terms: [] },
  '0-0-10-40-0': { terms: [] },
  '5-0-10-40-0': { terms: [] },
  '0-0-10-41-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-10-45-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-10-63-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-10-64-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-15-15-0': { terms: [
    { V: -1.400, gamma: 0, periodicity: 1 },
    { V: -8.300, gamma: 180, periodicity: 2 },
    { V: 1.000, gamma: 0, periodicity: 3 }
  ] },
  '5-0-15-15-0': { terms: [
    { V: -8.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-15-15-1': { terms: [
    { V: -1.663, gamma: 0, periodicity: 1 },
    { V: -8.408, gamma: 180, periodicity: 2 },
    { V: 1.433, gamma: 0, periodicity: 3 }
  ] },
  '0-1-15-15-71': { terms: [
    { V: -1.088, gamma: 0, periodicity: 1 },
    { V: -8.245, gamma: 180, periodicity: 2 },
    { V: 0.411, gamma: 0, periodicity: 3 }
  ] },
  '0-0-15-18-0': { terms: [
    { V: 0.160, gamma: 0, periodicity: 3 }
  ] },
  '0-0-15-19-0': { terms: [
    { V: 0.255, gamma: 0, periodicity: 3 }
  ] },
  '5-0-15-19-0': { terms: [
    { V: 0.255, gamma: 0, periodicity: 3 }
  ] },
  '0-0-15-20-0': { terms: [
    { V: 0.336, gamma: 0, periodicity: 3 }
  ] },
  '4-0-15-20-0': { terms: [
    { V: 0.336, gamma: 0, periodicity: 3 }
  ] },
  '0-0-15-22-0': { terms: [
    { V: 0.336, gamma: 0, periodicity: 3 }
  ] },
  '0-0-15-25-0': { terms: [
    { V: 0.358, gamma: 0, periodicity: 3 }
  ] },
  '4-0-15-25-0': { terms: [
    { V: 0.358, gamma: 0, periodicity: 3 }
  ] },
  '0-0-15-26-0': { terms: [
    { V: 0.537, gamma: 0, periodicity: 3 }
  ] },
  '0-0-15-30-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '4-0-15-30-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-15-37-0': { terms: [
    { V: 1.300, gamma: 180, periodicity: 2 }
  ] },
  '5-0-15-37-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-1-15-37-37': { terms: [
    { V: 2.177, gamma: 180, periodicity: 2 }
  ] },
  '0-71-15-37-37': { terms: [
    { V: 0.505, gamma: 180, periodicity: 2 },
    { V: 0.333, gamma: 0, periodicity: 3 }
  ] },
  '0-0-15-40-0': { terms: [
    { V: 0.424, gamma: 0, periodicity: 3 }
  ] },
  '0-0-15-43-0': { terms: [
    { V: 0.424, gamma: 0, periodicity: 3 }
  ] },
  '0-0-15-57-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-15-63-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-15-64-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-17-20-0': { terms: [] },
  '4-0-17-20-0': { terms: [] },
  '5-0-17-20-0': { terms: [] },
  '0-0-17-22-0': { terms: [] },
  '0-0-17-37-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-17-43-0': { terms: [
    { V: 3.795, gamma: 180, periodicity: 2 }
  ] },
  '0-0-18-20-0': { terms: [
    { V: 0.112, gamma: 0, periodicity: 3 }
  ] },
  '4-0-18-20-0': { terms: [
    { V: 0.112, gamma: 0, periodicity: 3 }
  ] },
  '5-0-18-20-0': { terms: [
    { V: 0.112, gamma: 0, periodicity: 3 }
  ] },
  '0-0-18-22-0': { terms: [
    { V: 0.112, gamma: 0, periodicity: 3 }
  ] },
  '0-0-18-37-0': { terms: [
    { V: -1.200, gamma: 180, periodicity: 2 },
    { V: -0.300, gamma: 0, periodicity: 3 }
  ] },
  '0-32-18-37-37': { terms: [
    { V: -0.173, gamma: 0, periodicity: 1 },
    { V: -0.965, gamma: 180, periodicity: 2 },
    { V: -0.610, gamma: 0, periodicity: 3 }
  ] },
  '0-39-18-37-37': { terms: [
    { V: -0.760, gamma: 180, periodicity: 2 },
    { V: 0.227, gamma: 0, periodicity: 3 }
  ] },
  '0-43-18-37-37': { terms: [
    { V: 0.228, gamma: 0, periodicity: 1 },
    { V: -1.741, gamma: 180, periodicity: 2 },
    { V: -0.371, gamma: 0, periodicity: 3 }
  ] },
  '0-0-18-39-0': { terms: [
    { V: 0.500, gamma: 0, periodicity: 3 }
  ] },
  '0-32-18-39-63': { terms: [
    { V: 0.687, gamma: 180, periodicity: 2 },
    { V: 0.680, gamma: 0, periodicity: 3 }
  ] },
  '0-37-18-39-63': { terms: [
    { V: -0.513, gamma: 180, periodicity: 2 },
    { V: 0.357, gamma: 0, periodicity: 3 }
  ] },
  '0-0-18-43-0': { terms: [
    { V: 0.350, gamma: 0, periodicity: 3 }
  ] },
  '4-0-18-43-0': { terms: [
    { V: 0.141, gamma: 0, periodicity: 3 }
  ] },
  '5-0-18-43-0': { terms: [
    { V: 0.141, gamma: 0, periodicity: 3 }
  ] },
  '0-1-18-43-1': { terms: [
    { V: -0.914, gamma: 0, periodicity: 1 },
    { V: -0.482, gamma: 180, periodicity: 2 },
    { V: 0.179, gamma: 0, periodicity: 3 }
  ] },
  '0-1-18-43-3': { terms: [
    { V: -0.392, gamma: 0, periodicity: 1 },
    { V: -2.724, gamma: 180, periodicity: 2 },
    { V: 0.312, gamma: 0, periodicity: 3 }
  ] },
  '0-1-18-43-28': { terms: [
    { V: -1.508, gamma: 0, periodicity: 1 },
    { V: -1.816, gamma: 180, periodicity: 2 },
    { V: -0.175, gamma: 0, periodicity: 3 }
  ] },
  '0-1-18-43-37': { terms: [
    { V: 0.823, gamma: 0, periodicity: 1 },
    { V: -1.220, gamma: 180, periodicity: 2 },
    { V: -0.770, gamma: 0, periodicity: 3 }
  ] },
  '0-32-18-43-1': { terms: [
    { V: 1.588, gamma: 0, periodicity: 1 },
    { V: 1.499, gamma: 180, periodicity: 2 },
    { V: 1.410, gamma: 0, periodicity: 3 }
  ] },
  '0-32-18-43-3': { terms: [
    { V: 0.653, gamma: 0, periodicity: 1 },
    { V: 0.254, gamma: 180, periodicity: 2 }
  ] },
  '0-32-18-43-28': { terms: [
    { V: 0.528, gamma: 0, periodicity: 1 },
    { V: 0.342, gamma: 180, periodicity: 2 }
  ] },
  '0-32-18-43-37': { terms: [
    { V: 0.812, gamma: 0, periodicity: 1 },
    { V: 1.513, gamma: 180, periodicity: 2 },
    { V: 1.266, gamma: 0, periodicity: 3 }
  ] },
  '0-37-18-43-1': { terms: [
    { V: -1.139, gamma: 0, periodicity: 1 },
    { V: -0.703, gamma: 180, periodicity: 2 },
    { V: 1.088, gamma: 0, periodicity: 3 }
  ] },
  '0-37-18-43-28': { terms: [
    { V: -2.014, gamma: 0, periodicity: 1 },
    { V: -1.646, gamma: 180, periodicity: 2 },
    { V: -2.068, gamma: 0, periodicity: 3 }
  ] },
  '0-37-18-43-37': { terms: [
    { V: -1.519, gamma: 0, periodicity: 1 },
    { V: -0.328, gamma: 180, periodicity: 2 },
    { V: 1.437, gamma: 0, periodicity: 3 }
  ] },
  '0-43-18-43-28': { terms: [
    { V: 3.011, gamma: 0, periodicity: 1 },
    { V: -1.405, gamma: 180, periodicity: 2 },
    { V: 2.038, gamma: 0, periodicity: 3 }
  ] },
  '0-0-18-48-0': { terms: [
    { V: 0.400, gamma: 0, periodicity: 3 }
  ] },
  '0-1-18-48-28': { terms: [
    { V: 1.767, gamma: 0, periodicity: 1 },
    { V: 1.606, gamma: 180, periodicity: 2 },
    { V: 0.408, gamma: 0, periodicity: 3 }
  ] },
  '0-32-18-48-28': { terms: [
    { V: -1.463, gamma: 0, periodicity: 1 },
    { V: -2.548, gamma: 180, periodicity: 2 },
    { V: 0.310, gamma: 0, periodicity: 3 }
  ] },
  '0-0-18-55-0': { terms: [] },
  '0-0-18-58-0': { terms: [] },
  '0-0-18-62-0': { terms: [
    { V: 0.500, gamma: 0, periodicity: 3 }
  ] },
  '0-1-18-62-1': { terms: [
    { V: -0.403, gamma: 0, periodicity: 1 },
    { V: -0.273, gamma: 180, periodicity: 2 },
    { V: 0.440, gamma: 0, periodicity: 3 }
  ] },
  '0-32-18-62-1': { terms: [
    { V: 0.291, gamma: 0, periodicity: 1 },
    { V: 0.385, gamma: 180, periodicity: 2 },
    { V: 0.582, gamma: 0, periodicity: 3 }
  ] },
  '0-0-18-63-0': { terms: [] },
  '0-0-18-64-0': { terms: [] },
  '0-0-18-80-0': { terms: [] },
  '0-0-19-20-0': { terms: [
    { V: 0.179, gamma: 0, periodicity: 3 }
  ] },
  '4-0-19-20-0': { terms: [
    { V: 0.179, gamma: 0, periodicity: 3 }
  ] },
  '0-0-19-37-0': { terms: [] },
  '0-0-19-40-0': { terms: [
    { V: 0.225, gamma: 0, periodicity: 3 }
  ] },
  '0-0-19-63-0': { terms: [] },
  '0-0-19-75-0': { terms: [] },
  '0-0-20-20-0': { terms: [
    { V: 0.200, gamma: 0, periodicity: 3 }
  ] },
  '4-0-20-20-0': { terms: [] },
  '5-0-20-20-0': { terms: [
    { V: 0.236, gamma: 0, periodicity: 3 }
  ] },
  '0-1-20-20-5': { terms: [
    { V: 0.067, gamma: 0, periodicity: 1 },
    { V: 0.081, gamma: 180, periodicity: 2 },
    { V: 0.347, gamma: 0, periodicity: 3 }
  ] },
  '0-1-20-20-20': { terms: [
    { V: -0.063, gamma: 0, periodicity: 1 },
    { V: -0.064, gamma: 180, periodicity: 2 },
    { V: 0.140, gamma: 0, periodicity: 3 }
  ] },
  '0-3-20-20-5': { terms: [
    { V: 0.083, gamma: 0, periodicity: 3 }
  ] },
  '0-3-20-20-20': { terms: [] },
  '0-5-20-20-5': { terms: [
    { V: 0.424, gamma: 0, periodicity: 3 }
  ] },
  '0-5-20-20-6': { terms: [
    { V: -0.080, gamma: 0, periodicity: 3 }
  ] },
  '0-5-20-20-8': { terms: [
    { V: 0.127, gamma: 180, periodicity: 2 },
    { V: 0.450, gamma: 0, periodicity: 3 }
  ] },
  '0-5-20-20-12': { terms: [
    { V: -0.072, gamma: 0, periodicity: 1 },
    { V: -0.269, gamma: 180, periodicity: 2 },
    { V: 0.439, gamma: 0, periodicity: 3 }
  ] },
  '0-5-20-20-20': { terms: [
    { V: -0.057, gamma: 0, periodicity: 1 },
    { V: 0.307, gamma: 0, periodicity: 3 }
  ] },
  '4-6-20-20-20': { terms: [] },
  '4-8-20-20-20': { terms: [
    { V: -0.091, gamma: 180, periodicity: 2 },
    { V: 0.192, gamma: 0, periodicity: 3 }
  ] },
  '0-12-20-20-20': { terms: [
    { V: 0.077, gamma: 0, periodicity: 1 },
    { V: 0.202, gamma: 180, periodicity: 2 },
    { V: 0.183, gamma: 0, periodicity: 3 }
  ] },
  '4-20-20-20-20': { terms: [] },
  '0-0-20-22-0': { terms: [
    { V: 0.236, gamma: 0, periodicity: 3 }
  ] },
  '4-0-20-22-0': { terms: [
    { V: 0.236, gamma: 0, periodicity: 3 }
  ] },
  '0-0-20-25-0': { terms: [
    { V: 0.251, gamma: 0, periodicity: 3 }
  ] },
  '4-0-20-25-0': { terms: [
    { V: 0.251, gamma: 0, periodicity: 3 }
  ] },
  '0-0-20-26-0': { terms: [
    { V: 0.376, gamma: 0, periodicity: 3 }
  ] },
  '4-0-20-26-0': { terms: [
    { V: 0.376, gamma: 0, periodicity: 3 }
  ] },
  '5-0-20-26-0': { terms: [
    { V: 0.376, gamma: 0, periodicity: 3 }
  ] },
  '0-0-20-30-0': { terms: [] },
  '2-0-20-30-0': { terms: [] },
  '4-0-20-30-0': { terms: [] },
  '0-0-20-30-30': { terms: [
    { V: -0.500, gamma: 0, periodicity: 3 }
  ] },
  '0-0-20-34-0': { terms: [
    { V: 0.198, gamma: 0, periodicity: 3 }
  ] },
  '4-0-20-34-0': { terms: [
    { V: 0.198, gamma: 0, periodicity: 3 }
  ] },
  '0-0-20-37-0': { terms: [] },
  '4-0-20-37-0': { terms: [] },
  '0-0-20-40-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '0-0-20-41-0': { terms: [] },
  '0-0-20-43-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '4-0-20-43-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '0-0-20-45-0': { terms: [] },
  '0-0-22-22-0': { terms: [
    { V: 0.236, gamma: 0, periodicity: 3 }
  ] },
  '4-0-22-22-0': { terms: [
    { V: 0.236, gamma: 0, periodicity: 3 }
  ] },
  '5-0-22-22-0': { terms: [
    { V: 0.236, gamma: 0, periodicity: 3 }
  ] },
  '0-0-22-30-0': { terms: [] },
  '4-0-22-30-0': { terms: [] },
  '0-0-22-34-0': { terms: [
    { V: 0.198, gamma: 0, periodicity: 3 }
  ] },
  '0-0-22-37-0': { terms: [] },
  '0-0-22-40-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '0-0-22-41-0': { terms: [] },
  '0-0-22-43-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '5-0-22-43-0': { terms: [
    { V: 0.297, gamma: 0, periodicity: 3 }
  ] },
  '0-0-22-45-0': { terms: [] },
  '0-0-25-25-0': { terms: [
    { V: 0.267, gamma: 0, periodicity: 3 }
  ] },
  '0-0-25-37-0': { terms: [] },
  '5-0-25-37-0': { terms: [] },
  '0-0-25-39-0': { terms: [] },
  '0-0-25-40-0': { terms: [
    { V: 0.316, gamma: 0, periodicity: 3 }
  ] },
  '5-0-25-40-0': { terms: [
    { V: 0.316, gamma: 0, periodicity: 3 }
  ] },
  '0-0-25-43-0': { terms: [
    { V: 0.250, gamma: 0, periodicity: 3 }
  ] },
  '0-1-25-43-1': { terms: [
    { V: -2.686, gamma: 0, periodicity: 1 },
    { V: -1.512, gamma: 180, periodicity: 2 },
    { V: 0.591, gamma: 0, periodicity: 3 }
  ] },
  '0-1-25-43-28': { terms: [
    { V: -3.730, gamma: 0, periodicity: 1 },
    { V: -0.531, gamma: 180, periodicity: 2 }
  ] },
  '0-32-25-43-1': { terms: [
    { V: 2.108, gamma: 0, periodicity: 1 },
    { V: 1.896, gamma: 180, periodicity: 2 },
    { V: 0.965, gamma: 0, periodicity: 3 }
  ] },
  '0-32-25-43-28': { terms: [
    { V: 2.977, gamma: 0, periodicity: 1 },
    { V: 0.732, gamma: 180, periodicity: 2 },
    { V: -0.502, gamma: 0, periodicity: 3 }
  ] },
  '0-0-25-57-0': { terms: [] },
  '0-0-25-63-0': { terms: [] },
  '0-0-26-26-0': { terms: [
    { V: 0.600, gamma: 0, periodicity: 3 }
  ] },
  '5-0-26-26-0': { terms: [
    { V: 0.600, gamma: 0, periodicity: 3 }
  ] },
  '0-0-26-34-0': { terms: [
    { V: 0.316, gamma: 0, periodicity: 3 }
  ] },
  '5-0-26-34-0': { terms: [
    { V: 0.316, gamma: 0, periodicity: 3 }
  ] },
  '0-0-26-37-0': { terms: [
    { V: 1.423, gamma: 180, periodicity: 2 }
  ] },
  '0-0-26-40-0': { terms: [
    { V: 0.474, gamma: 0, periodicity: 3 }
  ] },
  '0-0-30-30-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-30-30-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '4-0-30-30-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-30-40-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '1-0-30-67-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-34-37-0': { terms: [] },
  '0-0-34-43-0': { terms: [
    { V: 0.250, gamma: 0, periodicity: 3 }
  ] },
  '0-0-37-37-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-37-37-0': { terms: [
    { V: 2.000, gamma: 180, periodicity: 2 }
  ] },
  '4-0-37-37-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '5-0-37-37-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-37-37-5': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-37-37-37': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-2-37-37-5': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-2-37-37-37': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-3-37-37-5': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-3-37-37-37': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-37-37-5': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-37-37-6': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-37-37-15': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-37-37-18': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-37-37-37': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-37-37-40': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-37-37-43': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-6-37-37-37': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-15-37-37-37': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-18-37-37-37': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-37-37-37-37': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-37-37-37-40': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-37-37-37-43': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-38-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-39-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '1-0-37-39-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-40-0': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
  '5-0-37-40-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-37-37-40-1': { terms: [
    { V: 4.336, gamma: 180, periodicity: 2 },
    { V: 0.370, gamma: 0, periodicity: 3 }
  ] },
  '0-37-37-40-28': { terms: [
    { V: 0.715, gamma: 0, periodicity: 1 },
    { V: 2.628, gamma: 180, periodicity: 2 },
    { V: 3.355, gamma: 0, periodicity: 3 }
  ] },
  '0-0-37-41-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-43-0': { terms: [
    { V: 2.000, gamma: 180, periodicity: 2 },
    { V: 1.800, gamma: 0, periodicity: 3 }
  ] },
  '5-0-37-43-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-37-37-43-18': { terms: [
    { V: 0.372, gamma: 0, periodicity: 1 },
    { V: 2.284, gamma: 180, periodicity: 2 },
    { V: 2.034, gamma: 0, periodicity: 3 }
  ] },
  '0-37-37-43-28': { terms: [
    { V: 1.694, gamma: 180, periodicity: 2 },
    { V: 1.508, gamma: 0, periodicity: 3 }
  ] },
  '0-0-37-45-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-46-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-55-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-56-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-37-57-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-58-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-37-58-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-62-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-63-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-37-63-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-64-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-37-64-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-37-67-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-69-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-78-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-37-81-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-37-81-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-38-38-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-38-58-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-38-63-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-38-64-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-38-69-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-38-78-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-39-40-0': { terms: [] },
  '0-0-39-45-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-39-63-0': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-39-63-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '5-0-39-63-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-1-39-63-5': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-39-63-64': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
  '0-18-39-63-5': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
  '0-18-39-63-64': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
  '0-63-39-63-5': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
  '0-63-39-63-64': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-39-64-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '1-0-39-64-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-39-65-0': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-39-78-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-40-40-0': { terms: [
    { V: 0.375, gamma: 0, periodicity: 3 }
  ] },
  '0-0-40-45-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-40-46-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-40-54-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '2-0-40-54-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-40-63-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-40-64-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-40-78-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-41-41-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-41-55-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-41-62-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-41-80-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-43-43-0': { terms: [
    { V: 0.375, gamma: 0, periodicity: 3 }
  ] },
  '0-0-43-45-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-43-64-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-44-57-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-44-63-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-44-65-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-44-78-0': { terms: [
    { V: 2.846, gamma: 180, periodicity: 2 }
  ] },
  '0-0-44-80-0': { terms: [
    { V: 2.846, gamma: 180, periodicity: 2 }
  ] },
  '0-0-45-63-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-45-64-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-45-78-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-55-57-0': { terms: [
    { V: 10.000, gamma: 180, periodicity: 2 }
  ] },
  '2-0-55-57-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '5-0-55-57-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-1-55-57-5': { terms: [
    { V: 0.423, gamma: 0, periodicity: 1 },
    { V: 12.064, gamma: 180, periodicity: 2 },
    { V: 0.090, gamma: 0, periodicity: 3 }
  ] },
  '0-1-55-57-55': { terms: [
    { V: -0.428, gamma: 0, periodicity: 1 },
    { V: 12.044, gamma: 180, periodicity: 2 }
  ] },
  '0-36-55-57-5': { terms: [
    { V: -0.268, gamma: 0, periodicity: 1 },
    { V: 8.077, gamma: 180, periodicity: 2 },
    { V: -0.806, gamma: 0, periodicity: 3 }
  ] },
  '0-36-55-57-55': { terms: [
    { V: 0.273, gamma: 0, periodicity: 1 },
    { V: 8.025, gamma: 180, periodicity: 2 },
    { V: 0.692, gamma: 0, periodicity: 3 }
  ] },
  '0-0-55-62-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-55-64-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-55-80-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-56-57-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-1-56-57-56': { terms: [
    { V: 6.886, gamma: 180, periodicity: 2 },
    { V: -0.161, gamma: 0, periodicity: 3 }
  ] },
  '0-36-56-57-56': { terms: [
    { V: 4.688, gamma: 180, periodicity: 2 },
    { V: 0.107, gamma: 0, periodicity: 3 }
  ] },
  '0-0-56-63-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-56-80-0': { terms: [
    { V: 4.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-57-63-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '1-0-57-64-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-58-63-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-58-64-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-59-63-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-59-65-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-59-78-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-59-80-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-59-82-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-62-63-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-62-64-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '1-0-63-63-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-0-63-64-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-63-64-5': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-63-64-64': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-39-63-64-5': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-39-63-64-64': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-63-66-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-63-78-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-63-81-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-64-64-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '1-0-64-64-0': { terms: [
    { V: 1.800, gamma: 180, periodicity: 2 }
  ] },
  '0-5-64-64-5': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-5-64-64-63': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-63-64-64-63': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-64-65-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-64-66-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-64-78-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-64-81-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '5-0-64-81-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-64-82-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-65-66-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-65-78-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-65-81-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-65-82-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-66-66-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-66-78-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-66-81-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-67-67-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '5-0-67-67-0': { terms: [
    { V: 12.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-76-76-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-76-78-0': { terms: [
    { V: 3.600, gamma: 180, periodicity: 2 }
  ] },
  '0-0-78-78-0': { terms: [
    { V: 7.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-78-79-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-78-81-0': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-79-79-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-79-81-0': { terms: [
    { V: 6.000, gamma: 180, periodicity: 2 }
  ] },
  '0-0-80-81-0': { terms: [
    { V: 4.000, gamma: 180, periodicity: 2 }
  ] },
};
