import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { parse_mmd } from '../src/utils/mmd-parser';
import { assign_atom_types } from '../src/mmff94/atom-types';
import type { Molecule } from '../src/types';

// Canonical MMFF94 atom types for the validation suite, generated by
// tests/scripts/extract_suite_types.py from OpenBabel's MMFF94 setup.
// Molecules OpenBabel cannot set up (metals, dative, hypervalent) are
// absent from the reference and cannot be checked.
const suiteDir = join(__dirname, 'fixtures', 'validation-suite');
const reference = JSON.parse(
  readFileSync(join(suiteDir, 'mmff94-atom-types.json'), 'utf-8'),
) as { molecules: Record<string, number[]>; skipped: Record<string, string> };

// Molecules that must keep matching the reference exactly. Grown from the
// first baseline run (32/550 exact): every code here was type-exact when
// added, so a future typing change that breaks one of these is a
// regression. When a typing rule is deliberately changed, re-run the
// scoreboard, update this list (add newly-exact codes, drop regressed
// ones), and record the trade-off in the commit message.
const KNOWN_GOOD: string[] = [
  'BAOXLM01', 'CAFORM07', 'CAMALD03', 'CE05A', 'CITDIS', 'CIXWAH',
  'CILWUP11', 'CIYNUT', 'CO01A', 'CO08A', 'COGYAY', 'COKDEL',
  'COLZUY', 'COMDIR', 'COMWOQ', 'COMWUW', 'COVHUQ', 'CUDNEU',
  'CUYRAP', 'DADDAN', 'DAHNAB', 'DANCUQ', 'DAWYUV', 'DEPKEO',
  'DICYIX', 'DIHTET', 'DIKWID', 'DMEOXA01', 'DUJMEA', 'DUYNOA',
  'DUYRAQ', 'FAGLII', 'FAGVEO', 'FARMAM', 'FAZKUM', 'FILNOD',
  'FINBIN', 'FIZJED', 'FOJBEL', 'FORGOI', 'FOWVES', 'FOWZAS',
  'FUCMIZ', 'FUCMUL', 'FUHFAP', 'FUNXOB', 'FUPTOZ', 'FUTZEZ',
  'FUVDOP', 'GAKNIP', 'GEKXEZ', 'GIGMUE', 'GIKJIT', 'GIKTUP',
  'GOJCIR', 'HL13A', 'JAHYEW', 'JAKGUX', 'JEMWUT', 'JESFES',
  'JIYJAC', 'JIZWUK', 'KAGBOJ', 'KAVTEG', 'KECSUG', 'KEDYAT',
  'KOBYOP', 'KOHVIM', 'KOJKID', 'METBZC10', 'NH10A', 'NH23A',
  'SAFFOU', 'SAFFUA', 'SAVDOI', 'SAWKEG10', 'SEGJAP', 'SELFIY',
  'SI02A', 'SI03A', 'SR01A', 'SR05A', 'SR07A', 'TAFXIH',
  'TAJWAC', 'VABROF', 'VASDOI', 'VEJWOW', 'VEYBIK', 'VUXREL',
  'AR14A',
];

interface MoleculeResult {
  code: string;
  nAtoms: number;
  nMatch: number;
  diffs: string[];
}

describe('Atom typing vs OpenBabel reference (validation suite)', () => {
  it('reports the typing coverage scoreboard', () => {
    const molecules = parse_mmd(
      readFileSync(join(suiteDir, 'MMFF94.mmd'), 'utf-8'),
    );

    const results: MoleculeResult[] = [];
    let checked = 0;
    for (const mol of molecules) {
      const ref = reference.molecules[mol.name!];
      if (ref === undefined) continue; // no OpenBabel reference (skipped)
      checked++;

      const typed = assign_atom_types(mol);
      const diffs: string[] = [];
      let nMatch = 0;
      for (let a = 0; a < mol.atoms.length; a++) {
        if (typed.atom_types[a] === ref[a]) {
          nMatch++;
        } else {
          // Element + coordinates identify the atom; report which rule
          // the typing workstream should look at next.
          diffs.push(
            `${mol.atoms[a].element}${a} (ours ${typed.atom_types[a]} vs ref ${ref[a]})`,
          );
        }
      }
      results.push({
        code: mol.name!,
        nAtoms: mol.atoms.length,
        nMatch,
        diffs,
      });
    }

    const exact = results.filter(r => r.nMatch === r.nAtoms);
    const nearly = results.filter(r => r.nMatch >= 0.9 * r.nAtoms);
    const pct = (x: number) => ((100 * x) / checked).toFixed(1);

    console.log(`\nTyping coverage vs OpenBabel (${checked} reference molecules):`);
    console.log(`  exact:        ${exact.length} (${pct(exact.length)}%)`);
    console.log(`  ≥90% atoms:   ${nearly.length} (${pct(nearly.length)}%)`);
    console.log(`  exact codes:  ${exact.map(r => r.code).join(', ')}`);
    console.log(`  worst 10:`);
    results
      .sort((a, b) => a.nMatch / a.nAtoms - b.nMatch / b.nAtoms)
      .slice(0, 10)
      .forEach(r =>
        console.log(`    ${r.code.padEnd(10)} ${r.nMatch}/${r.nAtoms}  ${r.diffs.slice(0, 4).join('; ')}`),
      );

    // No reference coverage assertions yet — the scoreboard is the report.
    // KNOWN_GOOD pinning happens once the baseline is established.
    expect(checked).toBeGreaterThan(500);
  });

  it('keeps known-good molecules type-exact', () => {
    const molecules = parse_mmd(
      readFileSync(join(suiteDir, 'MMFF94.mmd'), 'utf-8'),
    );
    const byName = new Map<string, Molecule>(molecules.map(m => [m.name!, m]));
    for (const code of KNOWN_GOOD) {
      const mol = byName.get(code)!;
      const ref = reference.molecules[code]!;
      const typed = assign_atom_types(mol);
      expect(typed.atom_types, `${code} regressed`).toEqual(ref);
    }
  });
});
