import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { parse_mmd } from '../src/utils/mmd-parser';
import { assign_atom_types } from '../src/mmff94/atom-types';
import type { Molecule } from '../src/types';

// Canonical MMFF94 atom types for the validation suite, generated by
// tests/scripts/extract_suite_types.py from OpenBabel's MMFF94 setup.
// Molecules OpenBabel cannot set up (metals, dative, hypervalent) are
// absent from the reference and cannot be checked.
const suiteDir = join(__dirname, 'fixtures', 'validation-suite');
const reference = JSON.parse(
  readFileSync(join(suiteDir, 'mmff94-atom-types.json'), 'utf-8'),
) as { molecules: Record<string, number[]>; skipped: Record<string, string> };

// Molecules that must keep matching the reference exactly. Grown from the
// first baseline run (32/550 exact): every code here was type-exact when
// added, so a future typing change that breaks one of these is a
// regression. When a typing rule is deliberately changed, re-run the
// scoreboard, update this list (add newly-exact codes, drop regressed
// ones), and record the trade-off in the commit message.
const KNOWN_GOOD: string[] = [
  // Regenerated 2026-08-03 after the phosphate/sulfonate oxygen cluster:
  // P=O and S=O/S-O- type-32 rules, terminal-O count, H on cationic N (36),
  // H on P (71), acid/enol/phenol H (24/33/29), C=S -> 3, sulfine 74,
  // P 25/75/26. 241/550 type-exact (43.8%).
  'AGLYSL01', 'AMHTAR01', 'BAOXLM01', 'BIPDEJ02', 'BIPYCL01', 'BUPSLB10', 'BUPSLD10', 'BUYXEY10', 'CABWEH10',
  'CAFORM07', 'CALXES20', 'CAMALD03', 'CEWCUC10', 'CEWVIJ10', 'CEWYIM30', 'CILWUP11', 'CITDIS', 'CITNOI10',
  'CITPEA10', 'CIXWAH', 'CIYNUT', 'CIZFIA', 'COGYAY', 'COKDEL', 'COLZUY', 'COMDIR', 'COMWOQ',
  'COMWUW', 'CONFAM', 'CONLIA', 'CORDOC', 'COSFAR', 'COTMON', 'COTPEG', 'COVHUQ', 'COWTIR',
  'COXBAS', 'COYNAF', 'CUDNEU', 'CUDPOG', 'CUFFAK', 'CULHIA10', 'CULVEK', 'CUVFOO', 'CUVGAB',
  'CUVJOS', 'CUYRAP', 'DACSAB', 'DADDAN', 'DAHBAP', 'DAHNAB', 'DANCUQ', 'DAWYUV', 'DAYWEF',
  'DEBMOM01', 'DECJAW', 'DEDCIY', 'DEMBIG', 'DEPKEO', 'DEXGIW', 'DEZXEL', 'DICYIX', 'DIGCUR',
  'DIHTET', 'DIKWID', 'DIVWEK', 'DIYDIY', 'DIZPUX', 'DMEOXA01', 'DONFOB', 'DOTNIJ', 'DUBNET',
  'DUJHEV', 'DUJMEA', 'DUKWUB', 'DUMHIC', 'DUPTAJ', 'DUVHUX10', 'DUVXIB', 'DUWGAD', 'DUXTIZ',
  'DUYNOA', 'DUYRAQ', 'FAGLII', 'FAGVEO', 'FAGZOC', 'FAMHAC', 'FAMYUN', 'FARMAM', 'FAZKUM',
  'FEGSEP', 'FELYIE', 'FELYUQ', 'FENHAH', 'FENJIR', 'FENJUD', 'FESCAH', 'FETRUR', 'FIHXID',
  'FIKZOO10', 'FILNOD', 'FINBIN', 'FIVRAD', 'FIZJED', 'FOHYAC', 'FOJBEL', 'FOJPAV', 'FORGOI',
  'FOWVES', 'FOWZAS', 'FUCMIZ', 'FUCMUL', 'FUDPOJ', 'FUFDIT', 'FUHFAP', 'FUNXOB', 'FUPKIK',
  'FUPTOZ', 'FUSPEO', 'FUTZEZ', 'FUVDOP', 'FUVMUE', 'FUXXAX', 'GAHPIO', 'GAKNIP', 'GAKPEN',
  'GAPMEP', 'GAVMEV', 'GAWWOQ', 'GEHPUE', 'GEKXEZ', 'GIGMUE', 'GIKJIT', 'GIKNOD', 'GIKTUP',
  'GIPHES', 'GOHVUU', 'GOJCIR', 'HYTPRD01', 'JABGAU', 'JADLIJ', 'JAHYEW', 'JAKGUX', 'JALSOE',
  'JAWZEM', 'JECVUI', 'JELKUG', 'JEMHIS', 'JEMWUT', 'JESFES', 'JETJUN', 'JEWFAS', 'JEYBUK',
  'JIGRAS', 'JIKHUG', 'JINDOZ', 'JISZAM', 'JIYJAC', 'JIYTOA', 'JIZWUK', 'KAGBOJ', 'KASBOV',
  'KAVTEG', 'KECSIU', 'KECSUG', 'KEDYAT', 'KEJFOU', 'KHDFRM11', 'KICLAJ', 'KIMLEX01', 'KINWIN',
  'KOBYOP', 'KODFUE', 'KOFMEX', 'KOHVEI', 'KOHVIM', 'KOJGOF', 'KOJKID', 'METBZC10', 'NHOXAL06',
  'PHOSLA10', 'SAFFOU', 'SAFFUA', 'SALVEG', 'SAMXUZ', 'SAVDOI', 'SAWKEG10', 'SEFYIL', 'SEGJAP',
  'SEHBEM', 'SELFIY', 'SEMDIX', 'SETHAA', 'SIYLOB', 'SIZWUT', 'SURDOX02', 'TAFXIH', 'TAGVIG',
  'TAJWAC', 'VABROF', 'VALWOU', 'VASDOI', 'VAZHUZ', 'VEJWOW', 'VEYBIK', 'VEZBUX', 'VICKIB',
  'VIMHII', 'VOJGEG', 'VUWXUG', 'VUXREL', 'ZZZMVU10', 'ZZZVCQ01', 'AR14A', 'CA04A', 'CE05A',
  'CO01A', 'CO08A', 'NH10A', 'NH20A', 'NH22A', 'NH23A', 'OH10A', 'SR01A', 'SR05A',
  'SR07A', 'AN05A', 'HL13A', 'OC02A', 'PO02A', 'PR01A', 'PR02A', 'PR03A', 'SI02A',
  'SI03A', 'SO12A', 'SO16A', 'SO18A', 'BRMW1', 'CLMW1', 'FMW1',
];

interface MoleculeResult {
  code: string;
  nAtoms: number;
  nMatch: number;
  diffs: string[];
}

describe('Atom typing vs OpenBabel reference (validation suite)', () => {
  it('reports the typing coverage scoreboard', () => {
    const molecules = parse_mmd(
      readFileSync(join(suiteDir, 'MMFF94.mmd'), 'utf-8'),
    );

    const results: MoleculeResult[] = [];
    let checked = 0;
    for (const mol of molecules) {
      const ref = reference.molecules[mol.name!];
      if (ref === undefined) continue; // no OpenBabel reference (skipped)
      checked++;

      const typed = assign_atom_types(mol);
      const diffs: string[] = [];
      let nMatch = 0;
      for (let a = 0; a < mol.atoms.length; a++) {
        if (typed.atom_types[a] === ref[a]) {
          nMatch++;
        } else {
          // Element + coordinates identify the atom; report which rule
          // the typing workstream should look at next.
          diffs.push(
            `${mol.atoms[a].element}${a} (ours ${typed.atom_types[a]} vs ref ${ref[a]})`,
          );
        }
      }
      results.push({
        code: mol.name!,
        nAtoms: mol.atoms.length,
        nMatch,
        diffs,
      });
    }

    const exact = results.filter(r => r.nMatch === r.nAtoms);
    const nearly = results.filter(r => r.nMatch >= 0.9 * r.nAtoms);
    const pct = (x: number) => ((100 * x) / checked).toFixed(1);

    console.log(`\nTyping coverage vs OpenBabel (${checked} reference molecules):`);
    console.log(`  exact:        ${exact.length} (${pct(exact.length)}%)`);
    console.log(`  ≥90% atoms:   ${nearly.length} (${pct(nearly.length)}%)`);
    console.log(`  exact codes:  ${exact.map(r => r.code).join(', ')}`);
    console.log(`  worst 10:`);
    results
      .sort((a, b) => a.nMatch / a.nAtoms - b.nMatch / b.nAtoms)
      .slice(0, 10)
      .forEach(r =>
        console.log(`    ${r.code.padEnd(10)} ${r.nMatch}/${r.nAtoms}  ${r.diffs.slice(0, 4).join('; ')}`),
      );

    // No reference coverage assertions yet — the scoreboard is the report.
    // KNOWN_GOOD pinning happens once the baseline is established.
    expect(checked).toBeGreaterThan(500);
  });

  it('keeps known-good molecules type-exact', () => {
    const molecules = parse_mmd(
      readFileSync(join(suiteDir, 'MMFF94.mmd'), 'utf-8'),
    );
    const byName = new Map<string, Molecule>(molecules.map(m => [m.name!, m]));
    for (const code of KNOWN_GOOD) {
      const mol = byName.get(code)!;
      const ref = reference.molecules[code]!;
      const typed = assign_atom_types(mol);
      expect(typed.atom_types, `${code} regressed`).toEqual(ref);
    }
  });
});
