import { describe, it, expect } from 'vitest';
import { readFileSync } from 'fs';
import { join } from 'path';
import { parse_mmd } from '../src/utils/mmd-parser';
import { assign_atom_types } from '../src/mmff94/atom-types';
import type { Molecule } from '../src/types';

// Canonical MMFF94 atom types for the validation suite, generated by
// tests/scripts/extract_suite_types.py from OpenBabel's MMFF94 setup.
// Molecules OpenBabel cannot set up (metals, dative, hypervalent) are
// absent from the reference and cannot be checked.
const suiteDir = join(__dirname, 'fixtures', 'validation-suite');
const reference = JSON.parse(
  readFileSync(join(suiteDir, 'mmff94-atom-types.json'), 'utf-8'),
) as { molecules: Record<string, number[]>; skipped: Record<string, string> };

// Molecules that must keep matching the reference exactly. Grown from the
// first baseline run (32/550 exact): every code here was type-exact when
// added, so a future typing change that breaks one of these is a
// regression. When a typing rule is deliberately changed, re-run the
// scoreboard, update this list (add newly-exact codes, drop regressed
// ones), and record the trade-off in the commit message.
const KNOWN_GOOD: string[] = [
  // Regenerated 2026-08-03 after the amidine/sp-N cluster: C=N -> 3,
  // amidinium 57 by =N coordination, N3-on-sp2-C -> 40 (amidine,
  // enamine, aniline), amidinium/guanidinium N 55/56, nitrile N 42,
  // sulfonamide/cyanamide N 43, H on 40/43 -> 28, H on imine -> 27,
  // H on 55/56/81 -> 36, N-type pass, 4-ring alkene 30, cyclopropane
  // ring-size BFS fix. 512/550 type-exact (93.1%).
  'AGLYSL01', 'AMHTAR01', 'BAOXLM01', 'BBSPRT10', 'BEVJER10', 'BIPDEJ02', 'BIPYCL01', 'BIYBIU10', 'BODKOU',
  'BSALAP01', 'BUPSLB10', 'BUPSLD10', 'BUYTIY10', 'BUYTOE10', 'BUYXEY10', 'BYITOT02', 'CABWEH10', 'CAFORM07',
  'CAGREH10', 'CALXES20', 'CAMALD03', 'CEFMEN', 'CETROI01', 'CEWCUC10', 'CEWVIJ10', 'CEWYIM30', 'CIHWUL10',
  'CIKSEU10', 'CILDOQ', 'CILWUP11', 'CIMRUL10', 'CIPYAB10', 'CITDIS', 'CITNOI10', 'CITPEA10', 'CIVCEP02',
  'CIVLAU02', 'CIXWAH', 'CIYNUT', 'CIZFIA', 'CIZJAW', 'CIZYEP', 'COBKIN01', 'COCXUN', 'COGDEH',
  'COGYAY', 'COHKOZ', 'COKDEL', 'COLZUY', 'COMDIR', 'COMKAQ', 'COMWOQ', 'COMWUW', 'CONBAI',
  'CONFAM', 'CONLIA', 'CORDOC', 'COSFAR', 'COSWIQ', 'COTMON', 'COTPEG', 'COVHUQ', 'COVMAB',
  'COWTIR', 'COXBAS', 'COXZEU', 'COYMOS', 'COYNAF', 'COYVIV', 'CUBTUO', 'CUCDAF', 'CUCHOX',
  'CUDJAM', 'CUDNEU', 'CUDPOG', 'CUFFAK', 'CUGBEL', 'CULGEV10', 'CULHIA10', 'CULVEK', 'CUNVEM',
  'CURZIY', 'CUVFOO', 'CUVGAB', 'CUVJOS', 'CUYRAP', 'CYANAM01', 'DABHAP', 'DABLIB', 'DACSAB',
  'DACYIP', 'DADDAN', 'DADLAV', 'DADLEZ', 'DAGTUA', 'DAHBAP', 'DAHNAB', 'DAJXER', 'DAKDOI',
  'DANCUQ', 'DAPSUO03', 'DARDEF', 'DARXID', 'DAWYUV', 'DAYWEF', 'DAZVEF', 'DEBMOM01', 'DECJAW',
  'DECKUR', 'DEDCIY', 'DEDSIO', 'DEFTUD', 'DEFYUI', 'DEGRIQ', 'DEMBIG', 'DEPKEO', 'DESWUT',
  'DESYOP', 'DEWHOC', 'DEWJEU', 'DEXCIS', 'DEXGIW', 'DEZDUH', 'DEZNIF', 'DEZXEL', 'DHOADS01',
  'DICKIJ', 'DICYIX', 'DICYOD', 'DIDYOE', 'DIGCUR', 'DIHTET', 'DIKGAF', 'DIKGEJ', 'DIKWID',
  'DIKYUR', 'DILCOQ', 'DIPDAH10', 'DIPDIP10', 'DIRMIA', 'DISHES', 'DITYAG10', 'DIVTUX', 'DIVWEK',
  'DIXJEZ', 'DIYDIY', 'DIYPOQ', 'DIYPUW', 'DIZPUX', 'DMEOXA01', 'DOCFIK', 'DOCWUN', 'DODNOZ',
  'DODNUF', 'DOJPAT', 'DONFOB', 'DOSNOO', 'DOTNIJ', 'DOTWOY', 'DOWDEY', 'DOXZOF', 'DUBNET',
  'DUDMUK', 'DUGMUN', 'DUGWIL01', 'DUJHEV', 'DUJMEA', 'DUKWUB', 'DULTIN', 'DUMHIC', 'DUPTAJ',
  'DUVHUX10', 'DUVXIB', 'DUWGAD', 'DUWKUB', 'DUXTIZ', 'DUXWUO', 'DUXXAV', 'DUYNOA', 'DUYRAQ',
  'FACMIF', 'FADMIG', 'FADVEL', 'FAGCOF', 'FAGLII', 'FAGVEO', 'FAGZOC', 'FAHPUZ', 'FAHZET',
  'FAJWIW', 'FAMHAC', 'FAMYUN', 'FARMAM', 'FARSOG', 'FASGUB', 'FATLIV', 'FAXVAB', 'FAZBAJ',
  'FAZKUM', 'FECXEQ', 'FEGSEP', 'FEHDAX', 'FEJKIO', 'FELYIE', 'FELYUQ', 'FEMGEJ', 'FENHAH',
  'FENJIR', 'FENJOX', 'FENJUD', 'FEPWOM', 'FESCAH', 'FESMIZ', 'FETRUR', 'FETWOQ', 'FEVNUP',
  'FEZRUX', 'FIFGUW', 'FIGYID', 'FIHXID', 'FIKJAK', 'FIKZOO10', 'FILGEM', 'FILNOD', 'FINBIN',
  'FINPEX', 'FITGIY', 'FITSEG', 'FIVNUT', 'FIVRAD', 'FIZJED', 'FOBJUB01', 'FODTUN', 'FOGVIG01',
  'FOHXEF', 'FOHYAC', 'FOJBEL', 'FOJPAV', 'FONCOA', 'FORGOI', 'FORJIF', 'FORJUR', 'FOVHUT',
  'FOVJIJ', 'FOWBEY', 'FOWPOW', 'FOWVES', 'FOWZAS', 'FUCMIZ', 'FUCMUL', 'FUCWIJ', 'FUDPOJ',
  'FUDXUX', 'FUFDIT', 'FUHFAP', 'FUNXOB', 'FUPKIK', 'FUPTOZ', 'FUPZEV', 'FUSPEO', 'FUTCEC',
  'FUTZEZ', 'FUVDOP', 'FUVMUE', 'FUVNEP', 'FUWMOZ', 'FUXXAX', 'FUXZED', 'GADHEY', 'GAHPIO',
  'GAKGOO', 'GAKNIP', 'GAKPEN', 'GANHUY', 'GAPMEP', 'GAVMEV', 'GAWWOQ', 'GEHBOK', 'GEHPUE',
  'GEHXEW', 'GEKXEZ', 'GEMCEG', 'GEMCOQ', 'GEMDAD', 'GESNIB', 'GESSUS', 'GEWTAD', 'GIDJUY',
  'GIDTIW', 'GIGCEE', 'GIGMUE', 'GIHZEC', 'GIKJIT', 'GIKNOD', 'GIKTUP', 'GIMJIV', 'GINMUL',
  'GIPHES', 'GIRDOA01', 'GOHVUU', 'GOJCIR', 'HYTPRD01', 'ISTZCN10', 'JABGAU', 'JADLIJ', 'JAHKOS',
  'JAHTOB', 'JAHYEW', 'JAKGUX', 'JALSOE', 'JANMAM', 'JATBIP', 'JATCOW', 'JATMEW', 'JAWJIA',
  'JAWMAV', 'JAWZEM', 'JAZGOG', 'JAZVIP10', 'JAZZOZ10', 'JEBFEB01', 'JECVUI', 'JEFRAN', 'JEHCUU01',
  'JEHXOJ', 'JELKUG', 'JEMHIS', 'JEMWUT', 'JESFES', 'JETJUN', 'JEVXIR', 'JEWFAS', 'JEWPIK',
  'JEXREJ', 'JEYBUK', 'JIDHIN', 'JIGRAS', 'JIKHUG', 'JINDAL', 'JINDOZ', 'JIRJID', 'JISZAM',
  'JITMII', 'JIXBAT', 'JIYJAC', 'JIYTOA', 'JIZWUK', 'KAFXIY', 'KAGBOJ', 'KAKGOS', 'KAMCUW',
  'KANWEB', 'KANZOO', 'KARYAD', 'KASBOV', 'KATNAU', 'KAVTEG', 'KECSIU', 'KECSUG', 'KEDYAT',
  'KEFJEK', 'KEJFOU', 'KENHOA', 'KHDFRM11', 'KICCUU', 'KICGAE', 'KICLAJ', 'KIGKIU', 'KIMLEX01',
  'KINKUN', 'KINWEJ', 'KINWIN', 'KIRCOD', 'KIYGAA', 'KOBYOP', 'KOBZEG', 'KOCWUU', 'KODFUE',
  'KOFMEX', 'KOFNIC', 'KOHVEI', 'KOHVIM', 'KOJGOF', 'KOJKID', 'KOKMIG', 'KOLCUJ', 'METBZC10',
  'NHOXAL06', 'PHOSLA10', 'PHOSLB10', 'PIMTAZ01', 'SABNOY', 'SADXAW', 'SAFFOU', 'SAFFUA', 'SAHSOJ',
  'SAKGUG', 'SALVEG', 'SAMXUZ', 'SANKEX10', 'SAVDOI', 'SAWKEG10', 'SECDAF', 'SEFRAW', 'SEFYIL',
  'SEGFIT', 'SEGJAP', 'SEGLAR', 'SEGNEX', 'SEGWEG', 'SEHBEM', 'SEJDAM', 'SELFIY', 'SEMDIX',
  'SEMXOX', 'SETHAA', 'SETLIM', 'SEZMEP', 'SICPEZ', 'SIDFIU', 'SINMIL', 'SIYLOB', 'SIZJIU',
  'SIZWUT', 'SLFNMB04', 'SOJNEK', 'SOMKIO', 'SONZIE', 'SOPZEC', 'SURDOX02', 'TACLEO', 'TAFXIH',
  'TAGVIG', 'TAHMOE', 'TAJWAC', 'TAKHES', 'TAPSAE', 'TCYMPH02', 'TMTCHD01', 'VABLIT', 'VABROF',
  'VAJFAN', 'VALWOU', 'VAPZOB10', 'VASDOI', 'VATKAC', 'VAWMOV', 'VAZHUZ', 'VECSAX', 'VEDTED',
  'VEHZOX', 'VEJWOW', 'VENYUI', 'VEVDIJ', 'VEXMOA', 'VEYBIK', 'VEYWAX', 'VEZBUX', 'VICGAP',
  'VICGET', 'VICKIB', 'VIDKUO', 'VIGPEG', 'VIGTUA', 'VIHHID', 'VIMHII', 'VIWCOT', 'VIXRID',
  'VIXXOP', 'VIYPAU', 'VOBWOY', 'VOFBOH', 'VOFCAU', 'VOJGEG', 'VUWXUG', 'VUXGOK', 'VUXPUZ',
  'VUXREL', 'ZZZMVU10', 'ZZZVCQ01', 'AR14A', 'CA04A', 'CE05A', 'CO01A', 'CO08A', 'HL08A',
  'IM02A', 'NH10A', 'NH20A', 'NH22A', 'NH23A', 'OH10A', 'SR01A', 'SR05A', 'SR07A',
  'AN05A', 'HL11A', 'HL13A', 'OC02A', 'PO02A', 'PR01A', 'PR02A', 'PR03A', 'SI02A',
  'SI03A', 'SO07A', 'SO12A', 'SO16A', 'SO18A', 'BRMW1', 'CLMW1', 'FMW1',
];

interface MoleculeResult {
  code: string;
  nAtoms: number;
  nMatch: number;
  diffs: string[];
}

describe('Atom typing vs OpenBabel reference (validation suite)', () => {
  it('reports the typing coverage scoreboard', () => {
    const molecules = parse_mmd(
      readFileSync(join(suiteDir, 'MMFF94.mmd'), 'utf-8'),
    );

    const results: MoleculeResult[] = [];
    let checked = 0;
    for (const mol of molecules) {
      const ref = reference.molecules[mol.name!];
      if (ref === undefined) continue; // no OpenBabel reference (skipped)
      checked++;

      const typed = assign_atom_types(mol);
      const diffs: string[] = [];
      let nMatch = 0;
      for (let a = 0; a < mol.atoms.length; a++) {
        if (typed.atom_types[a] === ref[a]) {
          nMatch++;
        } else {
          // Element + coordinates identify the atom; report which rule
          // the typing workstream should look at next.
          diffs.push(
            `${mol.atoms[a].element}${a} (ours ${typed.atom_types[a]} vs ref ${ref[a]})`,
          );
        }
      }
      results.push({
        code: mol.name!,
        nAtoms: mol.atoms.length,
        nMatch,
        diffs,
      });
    }

    const exact = results.filter(r => r.nMatch === r.nAtoms);
    const nearly = results.filter(r => r.nMatch >= 0.9 * r.nAtoms);
    const pct = (x: number) => ((100 * x) / checked).toFixed(1);

    console.log(`\nTyping coverage vs OpenBabel (${checked} reference molecules):`);
    console.log(`  exact:        ${exact.length} (${pct(exact.length)}%)`);
    console.log(`  ≥90% atoms:   ${nearly.length} (${pct(nearly.length)}%)`);
    console.log(`  exact codes:  ${exact.map(r => r.code).join(', ')}`);
    console.log(`  worst 10:`);
    results
      .sort((a, b) => a.nMatch / a.nAtoms - b.nMatch / b.nAtoms)
      .slice(0, 10)
      .forEach(r =>
        console.log(`    ${r.code.padEnd(10)} ${r.nMatch}/${r.nAtoms}  ${r.diffs.slice(0, 4).join('; ')}`),
      );

    // No reference coverage assertions yet — the scoreboard is the report.
    // KNOWN_GOOD pinning happens once the baseline is established.
    expect(checked).toBeGreaterThan(500);
  });

  it('keeps known-good molecules type-exact', () => {
    const molecules = parse_mmd(
      readFileSync(join(suiteDir, 'MMFF94.mmd'), 'utf-8'),
    );
    const byName = new Map<string, Molecule>(molecules.map(m => [m.name!, m]));
    for (const code of KNOWN_GOOD) {
      const mol = byName.get(code)!;
      const ref = reference.molecules[code]!;
      const typed = assign_atom_types(mol);
      expect(typed.atom_types, `${code} regressed`).toEqual(ref);
    }
  });
});
