"""
Extract MMFF94 parameters from OpenBabel .par files and emit TypeScript
parameter tables with priority-column-in-key approach.

Usage: python scripts/extract-mmff94-par.py

Reads from temp_ob/data/*.par and writes to src/mmff94/parameters/*.ts.
"""

import os
import re
from collections import defaultdict

PAR_DIR = 'temp_ob/data'
OUT_DIR = 'src/mmff94/parameters'


def value(v: str) -> float | int:
    return int(v) if '.' not in v and v.lstrip('-').isdigit() else float(v)


def write_ts_header(f, description):
    f.write("// Auto-generated by scripts/extract-mmff94-par.py\n")
    f.write(f"// {description}\n")
    f.write("// Do not edit by hand.\n\n")


def parse_par(filename):
    """Read a .par file and return non-comment, non-empty data lines."""
    path = os.path.join(PAR_DIR, filename)
    lines = []
    with open(path) as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith('*') or stripped.startswith('$'):
                continue
            lines.append(stripped)
    return lines


# ── Bond parameters ────────────────────────────────────────────────────
# Format: p t1 t2 kb r0 source

def generate_bond():
    lines = parse_par('mmffbond.par')
    with open(os.path.join(OUT_DIR, 'bond.ts'), 'w') as f:
        write_ts_header(f, "Bond stretch parameters: k_b (mdyn/A), r0 (A).")
        f.write("export interface BondParams {\n")
        f.write("  k_b: number;\n")
        f.write("  r0: number;\n")
        f.write("}\n\n")
        f.write("export const BOND_PARAMS: Record<string, BondParams> = {\n")
        for line in lines:
            parts = line.split()
            if len(parts) < 6:
                continue
            p = parts[0]
            t1, t2 = parts[1], parts[2]
            kb, r0 = parts[3], parts[4]
            f.write(f"  '{p}-{t1}-{t2}': {{ k_b: {value(kb)}, r0: {value(r0)} }},\n")
        f.write("};\n")
    print(f"  [write] bond.ts ({len(lines)} entries)")


# ── Angle parameters ───────────────────────────────────────────────────
# Format: p t1 t2 t3 ka theta0 source

def generate_angle():
    lines = parse_par('mmffang.par')
    with open(os.path.join(OUT_DIR, 'angle.ts'), 'w') as f:
        write_ts_header(f, "Angle bend parameters: k_a (mdyn.A/rad^2), theta0 (deg).")
        f.write("export interface AngleParams {\n")
        f.write("  k_a: number;\n")
        f.write("  theta0: number;\n")
        f.write("}\n\n")
        f.write("export const ANGLE_PARAMS: Record<string, AngleParams> = {\n")
        for line in lines:
            parts = line.split()
            if len(parts) < 7:
                continue
            p = parts[0]
            t1, t2, t3 = parts[1], parts[2], parts[3]
            ka, th0 = parts[4], parts[5]
            f.write(f"  '{p}-{t1}-{t2}-{t3}': {{ k_a: {value(ka)}, theta0: {value(th0)} }},\n")
        f.write("};\n")
    print(f"  [write] angle.ts ({len(lines)} entries)")


# ── Stretch-bend parameters ────────────────────────────────────────────
# Format: p t1 t2 t3 kbaIJK kbaKJI source
# The stretch-bend energy formula uses k_sb values for both bonds (IJ and KJ).

def generate_stretch_bend():
    lines = parse_par('mmffstbn.par')
    with open(os.path.join(OUT_DIR, 'stretch-bend.ts'), 'w') as f:
        write_ts_header(f, "Stretch-bend cross term: k_sb_IJK, k_sb_KJI.")
        f.write("export interface StretchBendParams {\n")
        f.write("  k_sb_IJK: number;\n")
        f.write("  k_sb_KJI: number;\n")
        f.write("}\n\n")
        f.write("export const STRETCH_BEND_PARAMS: Record<string, StretchBendParams> = {\n")
        for line in lines:
            parts = line.split()
            if len(parts) < 7:
                continue
            p = parts[0]
            t1, t2, t3 = parts[1], parts[2], parts[3]
            kIJK, kKJI = parts[4], parts[5]
            f.write(f"  '{p}-{t1}-{t2}-{t3}': {{ k_sb_IJK: {value(kIJK)}, k_sb_KJI: {value(kKJI)} }},\n")
        f.write("};\n")
    print(f"  [write] stretch-bend.ts ({len(lines)} entries)")


# ── Torsion parameters ─────────────────────────────────────────────────
# Format: p t1 t2 t3 t4 V1 V2 V3 source [comment]
# V1 → n=1, gamma=0; V2 → n=2, gamma=pi; V3 → n=3, gamma=0

def generate_torsion():
    lines = parse_par('mmfftor.par')
    with open(os.path.join(OUT_DIR, 'torsion.ts'), 'w') as f:
        write_ts_header(f, "Torsion parameters: up to 3 Fourier terms per entry.")
        f.write("export interface TorsionTerm {\n")
        f.write("  V: number;\n")
        f.write("  gamma: number;     // phase in degrees\n")
        f.write("  periodicity: number;\n")
        f.write("}\n\n")
        f.write("export interface TorsionParams {\n")
        f.write("  terms: TorsionTerm[];\n")
        f.write("}\n\n")
        f.write("export const TORSION_PARAMS: Record<string, TorsionParams> = {\n")
        for line in lines:
            parts = line.split()
            if len(parts) < 8:
                continue
            p = parts[0]
            t1, t2, t3, t4 = parts[1], parts[2], parts[3], parts[4]
            V1, V2, V3 = parts[5], parts[6], parts[7]
            key = f"{p}-{t1}-{t2}-{t3}-{t4}"
            # Build up to 3 terms; only emit non-zero V's to keep tables compact
            terms = []
            v1 = float(V1)
            v2 = float(V2)
            v3 = float(V3)
            # V1: n=1, gamma=0
            if abs(v1) > 1e-10:
                terms.append(f"    {{ V: {V1}, gamma: 0, periodicity: 1 }}")
            # V2: n=2, gamma=180 (pi)
            if abs(v2) > 1e-10:
                terms.append(f"    {{ V: {V2}, gamma: 180, periodicity: 2 }}")
            # V3: n=3, gamma=0
            if abs(v3) > 1e-10:
                terms.append(f"    {{ V: {V3}, gamma: 0, periodicity: 3 }}")
            if terms:
                f.write(f"  '{key}': {{ terms: [\n")
                f.write(',\n'.join(terms))
                f.write(f"\n  ] }},\n")
            else:
                # All zeros: still include as a valid entry with empty terms
                f.write(f"  '{key}': {{ terms: [] }},\n")
        f.write("};\n")
    print(f"  [write] torsion.ts ({len(lines)} entries)")


# ── Van der Waals parameters ───────────────────────────────────────────
# Format: type alpha_i N_i A_i G_i DA Symb Origin
# A_i is used to compute R* = A_i * alpha_i^0.25 (see van-der-waals.ts).
# DA: 0 = neither, 1 = hydrogen bond donor, 2 = hydrogen bond acceptor

def generate_vdw():
    lines = parse_par('mmffvdw.par')
    with open(os.path.join(OUT_DIR, 'van-der-waals.ts'), 'w') as f:
        write_ts_header(f, "Van der Waals parameters per atom type.")
        f.write("export interface VdwParams {\n")
        f.write("  A_i: number;       // from .par file; R* = A_i * alpha_i^0.25\n")
        f.write("  alpha_i: number;   // polarizability (A^3)\n")
        f.write("  N_i: number;       // effective number of valence electrons\n")
        f.write("  G_i: number;       // dimensionless factor\n")
        f.write("  DA: number;        // hydrogen bond: 0=none, 1=donor, 2=acceptor\n")
        f.write("}\n\n")

        def parse_da(s: str) -> int:
            if s == 'D': return 1
            if s == 'A': return 2
            return 0

        f.write("export const VDW_PARAMS: Record<number, VdwParams> = {\n")
        for line in lines:
            parts = line.split()
            if len(parts) < 7:
                continue
            t = parts[0]
            alpha, N, A, G, da = parts[1], parts[2], parts[3], parts[4], parts[5]
            f.write(f"  {t}: {{ A_i: {value(A)}, alpha_i: {value(alpha)}, N_i: {value(N)}, G_i: {value(G)}, DA: {parse_da(da)} }},\n")
        f.write("};\n")
    print(f"  [write] van-der-waals.ts ({len(lines)} entries)")


# ── Bond charge increment parameters ───────────────────────────────────
# mmffchg.par: p t1 t2 bci source
# mmffpbci.par: p type pbci fcadj comment  (per-atom defaults)

def generate_bci():
    # Bond-specific BCI values
    lines = parse_par('mmffchg.par')
    with open(os.path.join(OUT_DIR, 'bci.ts'), 'w') as f:
        write_ts_header(f, "Bond charge increment (BCI) parameters.")
        f.write("export interface BciParams {\n")
        f.write("  bci: number;\n")
        f.write("}\n\n")
        f.write("export interface BciDefaultParams {\n")
        f.write("  pbci: number;     // per-atom default BCI\n")
        f.write("  fcadj: number;    // formal charge adjustment factor\n")
        f.write("}\n\n")
        f.write("export const BCI_PARAMS: Record<string, BciParams> = {\n")
        for line in lines:
            parts = line.split()
            if len(parts) < 5:
                continue
            p = parts[0]
            t1, t2 = parts[1], parts[2]
            bci = parts[3]
            f.write(f"  '{p}-{t1}-{t2}': {{ bci: {value(bci)} }},\n")
        f.write("};\n\n")
        # Per-atom defaults
        pbci_lines = parse_par('mmffpbci.par')
        f.write("export const BCI_DEFAULT_PARAMS: Record<number, BciDefaultParams> = {\n")
        for line in pbci_lines:
            parts = line.split()
            if len(parts) < 4:
                continue
            t = parts[1]  # parts[0] is priority, which is always 0
            pbci, fcadj = parts[2], parts[3]
            f.write(f"  {t}: {{ pbci: {value(pbci)}, fcadj: {value(fcadj)} }},\n")
        f.write("};\n")
    print(f"  [write] bci.ts ({len(lines)} bond + {len(pbci_lines)} per-atom entries)")


# ── Out-of-plane parameters ────────────────────────────────────────────
# Format: type_i type_j type_k type_l k_oop source [comment]
# Central atom is type_j. Entries with 0 are wildcards.
# NOTE: OOP has NO priority column — first field is type_i directly.
# Emit an explicit priority-0 prefix so the table matches every other
# table's "priority-type1-..." key convention and lookup_param() works.

def generate_oop():
    lines = parse_par('mmffoop.par')
    with open(os.path.join(OUT_DIR, 'out-of-plane.ts'), 'w') as f:
        write_ts_header(f, "Out-of-plane bending parameters: k_oop.")
        f.write("export interface OopParams {\n")
        f.write("  k_oop: number;\n")
        f.write("}\n\n")
        f.write("export const OOP_PARAMS: Record<string, OopParams> = {\n")
        for line in lines:
            parts = line.split()
            if len(parts) < 6:
                continue
            t1, t2, t3, t4 = parts[0], parts[1], parts[2], parts[3]
            k_oop = parts[4]
            f.write(f"  '0-{t1}-{t2}-{t3}-{t4}': {{ k_oop: {value(k_oop)} }},\n")
        f.write("};\n")
    print(f"  [write] out-of-plane.ts ({len(lines)} entries)")


# ── Atom type definitions ──────────────────────────────────────────────
# mmffdef.par: SYMBOL primary_type d1 d2 d3 d4 description
# mmffprop.par: atype aspec crd val pilp mltb arom lin sbmb

def generate_atom_types():
    def_lines = parse_par('mmffdef.par')
    prop_lines = parse_par('mmffprop.par')

    # Build element map from mmffprop.par
    elem_map = {}
    for line in prop_lines:
        parts = line.split()
        if len(parts) < 9:
            continue
        atype = int(parts[0])
        aspec = int(parts[1])
        # Atomic number to element symbol
        elem_symbols = {
            1: 'H', 5: 'B', 6: 'C', 7: 'N', 8: 'O', 9: 'F',
            14: 'Si', 15: 'P', 16: 'S', 17: 'Cl', 35: 'Br', 53: 'I',
        }
        elem = elem_symbols.get(aspec, f'X{aspec}')
        elem_map[atype] = elem

    with open(os.path.join(OUT_DIR, 'atom-types.ts'), 'w') as f:
        write_ts_header(f, "MMFF94 atom type definitions and properties.")
        f.write("export interface AtomTypeDef {\n")
        f.write("  type_num: number;\n")
        f.write("  symbol: string;    // chemical symbol (e.g., 'CR', 'C=C')\n")
        f.write("  element: string;   // element symbol (e.g., 'C', 'N', 'O')\n")
        f.write("  description: string;\n")
        f.write("  valence: number;   // from mmffprop.par (crd column)\n")
        f.write("}\n\n")
        f.write("export const ATOM_TYPES: Record<number, AtomTypeDef> = {\n")
        for line in def_lines:
            parts = line.split()
            if len(parts) < 6:
                continue
            sym = parts[0]
            primary_type = int(parts[1])
            desc = ' '.join(parts[5:])
            elem = elem_map.get(primary_type, '?')
            # Also get valence from prop_lines if possible
            valence = 0
            if primary_type in elem_map:
                for pl in prop_lines:
                    p_parts = pl.split()
                    if int(p_parts[0]) == primary_type:
                        valence = int(p_parts[2])
                        break
            f.write(f"  {primary_type}: {{ type_num: {primary_type}, symbol: '{sym}', element: '{elem}', description: '{desc}', valence: {valence} }},\n")
        f.write("};\n")
    print(f"  [write] atom-types.ts ({len(def_lines)} entries)")


# ── Parameter lookup helper ────────────────────────────────────────────
# Generates a helper module for priority-ordered parameter lookup

def generate_lookup():
    with open(os.path.join(OUT_DIR, 'lookup.ts'), 'w') as f:
        write_ts_header(f, "Priority-ordered parameter lookup helper.")
        f.write("""
/**
 * Look up a parameter entry with priority-ordered fallback.
 *
 * MMFF94 parameter tables store entries keyed as "priority-type1-type2-..."
 * where priority 0 is the default/primary entry and higher numbers are
 * context-specific alternatives. This helper tries entries in priority
 * order (0 first, then 1, 2, ...) and returns the first match.
 *
 * If no match is found, falls back to a wildcard variant where terminal
 * types are replaced with 0.
 */
export function lookup_param<T>(
  table: Record<string, T>,
  types: number[],
  max_priority: number = 5,
): T | undefined {

  // 1. Try exact match with priority 0, then 1, ..., max_priority
  const base_key = types.join('-');
  for (let p = 0; p <= max_priority; p++) {
    const key = `${p}-${base_key}`;
    if (key in table) return table[key];
  }

  // 2. Try with leading type as wildcard (0)
  if (types.length >= 2) {
    const wildcard_lead = [0, ...types.slice(1)].join('-');
    for (let p = 0; p <= max_priority; p++) {
      const key = `${p}-${wildcard_lead}`;
      if (key in table) return table[key];
    }
  }

  // 3. Try with trailing type as wildcard (0)
  if (types.length >= 2) {
    const wildcard_trail = [...types.slice(0, -1), 0].join('-');
    for (let p = 0; p <= max_priority; p++) {
      const key = `${p}-${wildcard_trail}`;
      if (key in table) return table[key];
    }
  }

  // 4. Try with both terminals as wildcard
  if (types.length >= 3) {
    const wildcard_both = [0, ...types.slice(1, -1), 0].join('-');
    for (let p = 0; p <= max_priority; p++) {
      const key = `${p}-${wildcard_both}`;
      if (key in table) return table[key];
    }
  }

  return undefined;
}

/**
 * Like lookup_param, but returns all matching entries (for cases where
 * multiple entries with different priorities are valid, and the caller
 * needs to choose based on context like bond order).
 */
export function lookup_all<T>(
  table: Record<string, T>,
  types: number[],
  max_priority: number = 5,
): T[] {
  const results: T[] = [];
  const base_key = types.join('-');
  for (let p = 0; p <= max_priority; p++) {
    const key = `${p}-${base_key}`;
    if (key in table) results.push(table[key]);
  }
  return results;
}
""")
    print("  [write] lookup.ts (helper functions)")


# ── Main ───────────────────────────────────────────────────────────────

def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    print("Generating parameter tables from OpenBabel .par files...")
    generate_bond()
    generate_angle()
    generate_stretch_bend()
    generate_torsion()
    generate_vdw()
    generate_bci()
    generate_oop()
    generate_atom_types()
    generate_lookup()

    print("\nDone. All parameter tables regenerated.")
    print("Run: ts files are in", OUT_DIR)


if __name__ == '__main__':
    main()
