"""
Extract MMFF94 parameters from OpenBabel text-format .prm files
and emit TypeScript parameter tables.

Usage: python scripts/extract-openbabel-params.py --input <openbabel/data/MMFF94/> --output src/mmff94/parameters/

This script reads the plain-text .prm files distributed with OpenBabel
(which contain only numerical parameter data from Halgren's publications)
and writes TypeScript source files with typed exports.

It is a format converter only — it implements no MMFF94 logic.
"""

import argparse
import os
import re
from collections import defaultdict
from typing import TextIO


SECTION_HEADERS = {
    'ATOMTYPE': 'atom-types.ts',
    'BOND': 'bond.ts',
    'ANGLE': 'angle.ts',
    'STRBND': 'stretch-bend.ts',
    'TORSION': 'torsion.ts',
    'VDW': 'van-der-waals.ts',
    'BCI': 'bci.ts',
    'OOP': 'out-of-plane.ts',
}

# ── helpers ──────────────────────────────────────────────────────────────

def parse_prm(filepath: str) -> dict[str, list[list[str]]]:
    """Split a .prm file into sections by header keyword.

    Returns { section_name: [row_fields, ...] } where each row_fields
    is the whitespace-split fields of one data line.
    """
    sections: dict[str, list[list[str]]] = defaultdict(list)
    current_section: str | None = None

    with open(filepath) as f:
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith('#'):
                continue
            # Check for section header (all-caps word at start of line)
            header_match = re.match(r'^([A-Z]+)\s', stripped)
            if header_match and header_match.group(1) in SECTION_HEADERS:
                current_section = header_match.group(1)
                continue
            if current_section:
                fields = stripped.split()
                if fields:
                    sections[current_section].append(fields)

    return sections


def write_ts_header(f: TextIO, description: str) -> None:
    """Write standard prologue for a generated TypeScript parameter file."""
    f.write("// Auto-generated by scripts/extract-openbabel-params.py\n")
    f.write(f"// {description}\n")
    f.write("// Do not edit by hand — re-run the extraction script.\n\n")


def value(v: str) -> float | int:
    """Parse a numeric string, returning int if no decimal point, else float."""
    return int(v) if '.' not in v and v.lstrip('-').isdigit() else float(v)


# ── section writers ──────────────────────────────────────────────────────

def write_atom_types(rows: list[list[str]], out: TextIO) -> None:
    write_ts_header(out, "MMFF94 atom type definitions.")
    out.write("export interface AtomTypeDef {\n")
    out.write("  type_num: number;\n")
    out.write("  element: string;\n")
    out.write("  description: string;\n")
    out.write("}\n\n")
    out.write("export const ATOM_TYPES: Record<number, AtomTypeDef> = {\n")
    for r in rows:
        num = r[0]
        elem = r[1]
        desc = ' '.join(r[2:])
        out.write(f"  {num}: {{ type_num: {num}, element: '{elem}', description: '{desc}' }},\n")
    out.write("};\n")


def write_bond_params(rows: list[list[str]], out: TextIO) -> None:
    write_ts_header(out, "Bond stretching parameters: k_b (mdyn/Å), r0 (Å).")
    out.write("export interface BondParams {\n")
    out.write("  k_b: number;\n")
    out.write("  r0: number;\n")
    out.write("}\n\n")
    out.write("/** Keyed by 'type1-type2' (lower type number first). */\n")
    out.write("export const BOND_PARAMS: Record<string, BondParams> = {\n")
    for r in rows:
        t1, t2 = r[0], r[1]
        kb, r0 = r[2], r[3]
        out.write(f"  '{t1}-{t2}': {{ k_b: {value(kb)}, r0: {value(r0)} }},\n")
    out.write("};\n")


def write_angle_params(rows: list[list[str]], out: TextIO) -> None:
    write_ts_header(out, "Angle bending parameters: k_a (mdyn·Å/rad²), θ₀ (degrees).")
    out.write("export interface AngleParams {\n")
    out.write("  k_a: number;\n")
    out.write("  theta0: number;\n")
    out.write("}\n\n")
    out.write("/** Keyed by 'type1-type2-type3'. */\n")
    out.write("export const ANGLE_PARAMS: Record<string, AngleParams> = {\n")
    for r in rows:
        t1, t2, t3 = r[0], r[1], r[2]
        ka, th0 = r[3], r[4]
        out.write(f"  '{t1}-{t2}-{t3}': {{ k_a: {value(ka)}, theta0: {value(th0)} }},\n")
    out.write("};\n")


def write_stretch_bend_params(rows: list[list[str]], out: TextIO) -> None:
    write_ts_header(out, "Stretch-bend cross term parameters: k_sb.")
    out.write("export interface StretchBendParams {\n")
    out.write("  k_sb: number;\n")
    out.write("}\n\n")
    out.write("/** Keyed by 'type1-type2-type3'. */\n")
    out.write("export const STRETCH_BEND_PARAMS: Record<string, StretchBendParams> = {\n")
    for r in rows:
        t1, t2, t3 = r[0], r[1], r[2]
        ksb = r[3]
        out.write(f"  '{t1}-{t2}-{t3}': {{ k_sb: {value(ksb)} }},\n")
    out.write("};\n")


def write_torsion_params(rows: list[list[str]], out: TextIO) -> None:
    write_ts_header(out, "Torsion parameters: up to three Fourier terms (V_n, γ_n, n).")
    out.write("export interface TorsionTerm {\n")
    out.write("  V: number;\n")
    out.write("  gamma: number;\n")
    out.write("  periodicity: number;\n")
    out.write("}\n\n")
    out.write("export interface TorsionParams {\n")
    out.write("  terms: TorsionTerm[];\n")
    out.write("}\n\n")
    out.write("/** Keyed by 'type1-type2-type3-type4'. */\n")
    out.write("export const TORSION_PARAMS: Record<string, TorsionParams> = {\n")
    # Group rows by the same (t1,t2,t3,t4) key — each row is one term
    groups: dict[str, list[list[str]]] = defaultdict(list)
    for r in rows:
        key = f"{r[0]}-{r[1]}-{r[2]}-{r[3]}"
        groups[key].append(r)
    for key, terms in groups.items():
        out.write(f"  '{key}': {{ terms: [\n")
        for r in terms:
            V, gamma, n = r[4], r[5], r[6]
            out.write(f"    {{ V: {value(V)}, gamma: {value(gamma)}, periodicity: {int(float(n))} }},\n")
        out.write(f"  ] }},\n")
    out.write("};\n")


def write_vdw_params(rows: list[list[str]], out: TextIO) -> None:
    write_ts_header(out, "Van der Waals parameters: R* (Å), ε (kcal/mol), G_i, α_i, N_i.")
    out.write("export interface VdwParams {\n")
    out.write("  R_star: number;\n")
    out.write("  epsilon: number;\n")
    out.write("  G_i: number;\n")
    out.write("  alpha_i: number;\n")
    out.write("  N_i: number;\n")
    out.write("}\n\n")
    out.write("/** Keyed by atom type number. */\n")
    out.write("export const VDW_PARAMS: Record<number, VdwParams> = {\n")
    for r in rows:
        t = r[0]
        Rstar, eps, Gi, ai, Ni = r[1], r[2], r[3], r[4], r[5]
        out.write(f"  {t}: {{ R_star: {value(Rstar)}, epsilon: {value(eps)}, G_i: {value(Gi)}, alpha_i: {value(ai)}, N_i: {value(Ni)} }},\n")
    out.write("};\n")


def write_bci_params(rows: list[list[str]], out: TextIO) -> None:
    write_ts_header(out, "Bond charge increment parameters.")
    out.write("export interface BciParams {\n")
    out.write("  bci: number;\n")
    out.write("}\n\n")
    out.write("/** Keyed by 'type1-type2'. */\n")
    out.write("export const BCI_PARAMS: Record<string, BciParams> = {\n")
    for r in rows:
        t1, t2 = r[0], r[1]
        bci = r[2]
        out.write(f"  '{t1}-{t2}': {{ bci: {value(bci)} }},\n")
    out.write("};\n")


def write_oop_params(rows: list[list[str]], out: TextIO) -> None:
    write_ts_header(out, "Out-of-plane bending parameters: k_oop.")
    out.write("export interface OopParams {\n")
    out.write("  k_oop: number;\n")
    out.write("}\n\n")
    out.write("/** Keyed by central atom type. */\n")
    out.write("export const OOP_PARAMS: Record<number, OopParams> = {\n")
    for r in rows:
        t = r[0]
        k = r[1]
        out.write(f"  {t}: {{ k_oop: {value(k)} }},\n")
    out.write("};\n")


SECTION_WRITERS = {
    'ATOMTYPE': write_atom_types,
    'BOND': write_bond_params,
    'ANGLE': write_angle_params,
    'STRBND': write_stretch_bend_params,
    'TORSION': write_torsion_params,
    'VDW': write_vdw_params,
    'BCI': write_bci_params,
    'OOP': write_oop_params,
}


# ── main ─────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description="Extract MMFF94 parameters from OpenBabel .prm files to TypeScript.")
    parser.add_argument('--input', required=True, help='Path to OpenBabel data/MMFF94/ directory')
    parser.add_argument('--output', required=True, help='Path to src/mmff94/parameters/ output directory')
    args = parser.parse_args()

    os.makedirs(args.output, exist_ok=True)

    # OpenBabel stores MMFF94 data in multiple .prm files
    # We scan all .prm files, collect sections, then write one output file per section
    all_sections: dict[str, list[list[str]]] = defaultdict(list)

    for filename in sorted(os.listdir(args.input)):
        if not filename.endswith('.prm'):
            continue
        filepath = os.path.join(args.input, filename)
        sections = parse_prm(filepath)
        for section_name, rows in sections.items():
            all_sections[section_name].extend(rows)

    # Write each section to its corresponding output file
    for section_name, output_filename in SECTION_HEADERS.items():
        if section_name not in all_sections:
            print(f"  [skip] {section_name} — no data found")
            continue
        output_path = os.path.join(args.output, output_filename)
        writer = SECTION_WRITERS[section_name]
        with open(output_path, 'w') as f:
            writer(all_sections[section_name], f)
        print(f"  [write] {output_path} ({len(all_sections[section_name])} entries)")

    print("Done.")


if __name__ == '__main__':
    main()
